USE userData;

insert into teams (teamName, wins,loses)
values ('Arizona Cardinals', 3,4),
	('Atlanta Falcons',4,3),
	('Baltimore Ravens',4,3),
	('Buffalo Bills',5,2),
	('Carolina Panthers',1,6),
	('Chicago Bears',4,2),
	('Cincinnati Bengals',3,4),
	('Cleveland Browns',1,6),
	('Dallas Cowboys',3,3),
	('Denver Broncos',4,3),
	('Detroit Lions',5,1),
	('Green Bay Packers',5,2),
	('Houston Texans',5,2),
	('Indianapolis Colts',4,3),
	('Jacksonville Jaguars',2,5),
	('Kansas City Chiefs',6,0),
	('Los Angeles Chargers',3,3),
	('Los Angeles Rams',2,4),
	('Las Vegas Raiders',2,5),
	('Miami Dolphins',2,4),
	('Minnesota Vikings',5,1),
	('New England Patriots',1,6),
	('New Orleans Saints',2,5),
	('New York Giants',2,5),
	('New York Jets',2,5),
	('Philadelphia Eagles',4,2),
	('Pittsburgh Steelers',5,2),
	('San Francisco 49ers',3,4),
	('Seattle Seahawks',4,3),
	('Tampa Bay Buccaneers',4,3),
	('Tennessee Titans',1,5),
	('Washington Commanders',5,2);

insert into players (playerNumber, playerName, playerPosition, playerTeam, id)
values (74, 'Isaiah Adams', 'OT', 'Arizona Cardinals', 1),
(3, 'Budda Baker', 'DB', 'Arizona Cardinals', 1),
(51, 'Krys Barnes', 'LB', 'Arizona Cardinals', 1),
(68, 'Kelvin Beachum', 'OT', 'Arizona Cardinals', 1),
(33, 'Trey Benson', 'RB', 'Arizona Cardinals', 1),
(32, 'Joey Blount', 'DB', 'Arizona Cardinals', 1),
(46, 'Aaron Brewer', 'LS', 'Arizona Cardinals', 1),
(62, 'Evan Brown', 'C', 'Arizona Cardinals', 1),
(13, 'KeiTrel Clark', 'DB', 'Arizona Cardinals', 1),
(91, 'L.J. Collier', 'DE', 'Arizona Cardinals', 1),
(25, 'Zaven Collins', 'LB', 'Arizona Cardinals', 1),
(63, 'Trystan Colon-Castillo', 'OG', 'Arizona Cardinals', 1),
(6, 'James Conner', 'RB', 'Arizona Cardinals', 1),
(20, 'DeeJay Dallas', 'RB', 'Arizona Cardinals', 1),
(31, 'Emari Demercado', 'RB', 'Arizona Cardinals', 1),
(52, 'Victor Dimukeje', 'LB', 'Arizona Cardinals', 1),
(4, 'Greg Dortch', 'WR', 'Arizona Cardinals', 1),
(72, 'Hjalte Froholdt', 'OG', 'Arizona Cardinals', 1),
(59, 'Jon Gaines', 'OG', 'Arizona Cardinals', 1),
(12, 'Blake Gillikin', 'P', 'Arizona Cardinals', 1),
(30, 'Darren Hall', 'DB', 'Arizona Cardinals', 1),
(18, 'Marvin Harrison', 'WR', 'Arizona Cardinals', 1),
(67, 'Charlie Heck', 'OT', 'Arizona Cardinals', 1),
(84, 'Elijah Higgins', 'TE', 'Arizona Cardinals', 1),
(70, 'Paris Johnson', 'OT', 'Arizona Cardinals', 1),
(75, 'Christian Jones', 'OT', 'Arizona Cardinals', 1),
(96, 'Naquan Jones', 'DT', 'Arizona Cardinals', 1),
(17, 'Zay Jones', 'WR', 'Arizona Cardinals', 1),
(98, 'Roy Lopez', 'DT', 'Arizona Cardinals', 1),
(43, 'Jesse Luketa', 'LB', 'Arizona Cardinals', 1),
(85, 'Trey McBride', 'TE', 'Arizona Cardinals', 1),
(16, 'Max Melton', 'DB', 'Arizona Cardinals', 1),
(23, 'Sean Murphy-Bunting', 'DB', 'Arizona Cardinals', 1),
(1, 'Kyler Murray', 'QB', 'Arizona Cardinals', 1),
(58, 'Julian Okwara', 'LB', 'Arizona Cardinals', 1),
(44, 'Owen Pappoe', 'LB', 'Arizona Cardinals', 1),
(0, 'Zach Pascal', 'WR', 'Arizona Cardinals', 1),
(87, 'Tip Reiman', 'TE', 'Arizona Cardinals', 1),
(56, 'Darius Robinson', 'DT', 'Arizona Cardinals', 1),
(38, 'Chad Ryland', 'K', 'Arizona Cardinals', 1),
(55, 'Dante Stills', 'DE', 'Arizona Cardinals', 1),
(42, 'Dadrion Taylor', 'DB', 'Arizona Cardinals', 1),
(24, 'Starling Thomas', 'DB', 'Arizona Cardinals', 1),
(54, 'Xavier Thomas', 'LB', 'Arizona Cardinals', 1),
(34, 'Jalen Thompson', 'DB', 'Arizona Cardinals', 1),
(95, 'Khyiris Tonga', 'DT', 'Arizona Cardinals', 1),
(15, 'Clayton Tune', 'QB', 'Arizona Cardinals', 1),
(81, 'Travis Vokolek', 'TE', 'Arizona Cardinals', 1),
(89, 'Xavier Weaver', 'WR', 'Arizona Cardinals', 1),
(7, 'Kyzir White', 'LB', 'Arizona Cardinals', 1),
(21, 'Garrett Williams', 'DB', 'Arizona Cardinals', 1),
(2, 'Mack Wilson', 'LB', 'Arizona Cardinals', 1),
(14, 'Michael Wilson', 'WR', 'Arizona Cardinals', 1),
(20, 'DeAundre Alford', 'DB', 'Atlanta Falcons', 2),
(25, 'Tyler Allgeier', 'RB', 'Atlanta Falcons', 2),
(44, 'Troy Andersen', 'LB', 'Atlanta Falcons', 2),
(3, 'Jessie Bates III', 'DB', 'Atlanta Falcons', 2),
(65, 'Matthew Bergeron', 'OT', 'Atlanta Falcons', 2),
(40, 'JD Bertrand', 'LB', 'Atlanta Falcons', 2),
(35, 'Natrone Brooks', 'DB', 'Atlanta Falcons', 2),
(18, 'Kirk Cousins', 'QB', 'Atlanta Falcons', 2),
(54, 'Brandon Dorlus', 'DT', 'Atlanta Falcons', 2),
(85, 'Ross Dwelley', 'TE', 'Atlanta Falcons', 2),
(17, 'Arnold Ebiketie', 'LB', 'Atlanta Falcons', 2),
(55, 'Kaden Elliss', 'LB', 'Atlanta Falcons', 2),
(54, 'Rashaan Evans', 'LB', 'Atlanta Falcons', 2),
(99, 'Eddie Goldman', 'DT', 'Atlanta Falcons', 2),
(95, 'TaQuon Graham', 'DT', 'Atlanta Falcons', 2),
(27, 'Richie Grant', 'DB', 'Atlanta Falcons', 2),
(56, 'Jovaughn Gwyn', 'OG', 'Atlanta Falcons', 2),
(33, 'Antonio Hamilton', 'DB', 'Atlanta Falcons', 2),
(91, 'Demone Harris', 'DE', 'Atlanta Falcons', 2),
(96, 'Zach Harrison', 'DE', 'Atlanta Falcons', 2),
(61, 'Matt Hennessy', 'C', 'Atlanta Falcons', 2),
(68, 'Kyle Hinton', 'OG', 'Atlanta Falcons', 2),
(12, 'Khadarel Hodge', 'WR', 'Atlanta Falcons', 2),
(21, 'Mike Hughes', 'DB', 'Atlanta Falcons', 2),
(97, 'Grady Jarrett', 'DT', 'Atlanta Falcons', 2),
(15, 'Matt Judon', 'LB', 'Atlanta Falcons', 2),
(32, 'Kevin King', 'DB', 'Atlanta Falcons', 2),
(6, 'Younghoe Koo', 'K', 'Atlanta Falcons', 2),
(53, 'Nate Landman', 'LB', 'Atlanta Falcons', 2),
(63, 'Chris Lindstrom', 'OG', 'Atlanta Falcons', 2),
(5, 'Drake London', 'WR', 'Atlanta Falcons', 2),
(51, 'DeAngelo Malone', 'LB', 'Atlanta Falcons', 2),
(70, 'Jake Matthews', 'OT', 'Atlanta Falcons', 2),
(30, 'Jase McClellan', 'RB', 'Atlanta Falcons', 2),
(34, 'Ray Ray McCloud', 'WR', 'Atlanta Falcons', 2),
(49, 'Liam McCullough', 'LS', 'Atlanta Falcons', 2),
(76, 'Kaleb McGary', 'OT', 'Atlanta Falcons', 2),
(1, 'Darnell Mooney', 'WR', 'Atlanta Falcons', 2),
(64, 'Ryan Neuzil', 'OG', 'Atlanta Falcons', 2),
(77, 'Storm Norton', 'OT', 'Atlanta Falcons', 2),
(90, 'David Onyemata', 'DT', 'Atlanta Falcons', 2),
(75, 'Brandon Parker', 'OT', 'Atlanta Falcons', 2),
(9, 'Michael Penix', 'QB', 'Atlanta Falcons', 2),
(22, 'Clark Phillips', 'DB', 'Atlanta Falcons', 2),
(13, 'Bradley Pinion', 'P', 'Atlanta Falcons', 2),
(8, 'Kyle Pitts', 'TE', 'Atlanta Falcons', 2),
(7, 'Bijan Robinson', 'RB', 'Atlanta Falcons', 2),
(31, 'Justin Simmons', 'DB', 'Atlanta Falcons', 2),
(50, 'James Smith-Williams', 'DE', 'Atlanta Falcons', 2),
(93, 'Kentavius Street', 'DT', 'Atlanta Falcons', 2),
(24, 'A.J. Terrell', 'DB', 'Atlanta Falcons', 2),
(82, 'Casey Washington', 'WR', 'Atlanta Falcons', 2),
(71, 'Elijah Wilkinson', 'OG', 'Atlanta Falcons', 2),
(26, 'Avery Williams', 'RB', 'Atlanta Falcons', 2),
(89, 'Charlie Woerner', 'TE', 'Atlanta Falcons', 2),
(15, 'Nelson Agholor', 'WR', 'Baltimore Ravens', 3),
(26, 'Rasheen Ali', 'RB', 'Baltimore Ravens', 3),
(89, 'Mark Andrews', 'TE', 'Baltimore Ravens', 3),
(5, 'Jalyn Armour-Davis', 'DB', 'Baltimore Ravens', 3),
(7, 'Rashod Bateman', 'WR', 'Baltimore Ravens', 3),
(49, 'Chris Board', 'LB', 'Baltimore Ravens', 3),
(24, 'Beau Brade', 'DB', 'Baltimore Ravens', 3),
(66, 'Ben Cleveland', 'OG', 'Baltimore Ravens', 3),
(38, 'Chris Collier', 'RB', 'Baltimore Ravens', 3),
(77, 'Daniel Faalele', 'OG', 'Baltimore Ravens', 3),
(4, 'Zay Flowers', 'WR', 'Baltimore Ravens', 3),
(14, 'Kyle Hamilton', 'DB', 'Baltimore Ravens', 3),
(40, 'Malik Harrison', 'LB', 'Baltimore Ravens', 3),
(22, 'Derrick Henry', 'RB', 'Baltimore Ravens', 3),
(43, 'Justice Hill', 'RB', 'Baltimore Ravens', 3),
(44, 'Marlon Humphrey', 'DB', 'Baltimore Ravens', 3),
(50, 'Adisa Isaac', 'LB', 'Baltimore Ravens', 3),
(39, 'Eddie Jackson', 'DB', 'Baltimore Ravens', 3),
(8, 'Lamar Jackson', 'QB', 'Baltimore Ravens', 3),
(18, 'Diontae Johnson', 'WR', 'Baltimore Ravens', 3),
(17, 'Josh Johnson', 'QB', 'Baltimore Ravens', 3),
(74, 'Josh Jones', 'OT', 'Baltimore Ravens', 3),
(98, 'Travis Jones', 'DT', 'Baltimore Ravens', 3),
(28, 'Sanoussi Kane', 'DB', 'Baltimore Ravens', 3),
(88, 'Charlie Kolar', 'TE', 'Baltimore Ravens', 3),
(80, 'Isaiah Likely', 'TE', 'Baltimore Ravens', 3),
(64, 'Tyler Linderbaum', 'C', 'Baltimore Ravens', 3),
(92, 'Justin Madubuike', 'DT', 'Baltimore Ravens', 3),
(10, 'Arthur Maulet', 'DB', 'Baltimore Ravens', 3),
(65, 'Patrick Mekari', 'OT', 'Baltimore Ravens', 3),
(46, 'Nick Moore', 'LS', 'Baltimore Ravens', 3),
(91, 'Yannick Ngakoue', 'LB', 'Baltimore Ravens', 3),
(90, 'David Ojabo', 'LB', 'Baltimore Ravens', 3),
(99, 'Jayson Oweh', 'LB', 'Baltimore Ravens', 3),
(42, 'Patrick Ricard', 'RB', 'Baltimore Ravens', 3),
(95, 'Tavius Robinson', 'LB', 'Baltimore Ravens', 3),
(70, 'Roger Rosengarten', 'OT', 'Baltimore Ravens', 3),
(61, 'Nick Samac', 'C', 'Baltimore Ravens', 3),
(23, 'Trenton Simpson', 'LB', 'Baltimore Ravens', 3),
(0, 'Roquan Smith', 'LB', 'Baltimore Ravens', 3),
(79, 'Ronnie Stanley', 'OT', 'Baltimore Ravens', 3),
(21, 'Brandon Stephens', 'DB', 'Baltimore Ravens', 3),
(11, 'Jordan Stout', 'P', 'Baltimore Ravens', 3),
(9, 'Justin Tucker', 'K', 'Baltimore Ravens', 3),
(69, 'Josh Tupou', 'DT', 'Baltimore Ravens', 3),
(97, 'Brent Urban', 'DE', 'Baltimore Ravens', 3),
(53, 'Kyle Van Noy', 'LB', 'Baltimore Ravens', 3),
(72, 'Andrew Vorhees', 'OG', 'Baltimore Ravens', 3),
(81, 'Devontez Walker', 'WR', 'Baltimore Ravens', 3),
(16, 'Tylan Wallace', 'WR', 'Baltimore Ravens', 3),
(29, 'ArDarius Washington', 'DB', 'Baltimore Ravens', 3),
(96, 'Broderick Washington', 'DT', 'Baltimore Ravens', 3),
(2, 'Nate Wiggins', 'DB', 'Baltimore Ravens', 3),
(32, 'Marcus Williams', 'DB', 'Baltimore Ravens', 3),
(93, 'Chris Wormley', 'DE', 'Baltimore Ravens', 3),
(17, 'Josh Allen', 'QB', 'Buffalo Bills', 4),
(70, 'Alec Anderson', 'OT', 'Buffalo Bills', 4),
(44, 'Joe Andreessen', 'LB', 'Buffalo Bills', 4),
(51, 'Eli Ankou', 'DT', 'Buffalo Bills', 4),
(2, 'Tyler Bass', 'K', 'Buffalo Bills', 4),
(47, 'Christian Benford', 'DB', 'Buffalo Bills', 4),
(43, 'Terrel Bernard', 'LB', 'Buffalo Bills', 4),
(24, 'Cole Bishop', 'DB', 'Buffalo Bills', 4),
(79, 'Spencer Brown', 'OT', 'Buffalo Bills', 4),
(77, 'William Clapp', 'C', 'Buffalo Bills', 4),
(29, 'Brandon Codrington', 'DB', 'Buffalo Bills', 4),
(0, 'Keon Coleman', 'WR', 'Buffalo Bills', 4),
(4, 'James Cook', 'RB', 'Buffalo Bills', 4),
(18, 'Amari Cooper', 'WR', 'Buffalo Bills', 4),
(22, 'ReMahn Davis', 'RB', 'Buffalo Bills', 4),
(73, 'Dion Dawkins', 'OT', 'Buffalo Bills', 4),
(31, 'Rasul Douglas', 'DB', 'Buffalo Bills', 4),
(76, 'David Edwards', 'OG', 'Buffalo Bills', 4),
(21, 'Mike Edwards', 'DB', 'Buffalo Bills', 4),
(5, 'Kaiir Elam', 'DB', 'Buffalo Bills', 4),
(57, 'A.J. Epenesa', 'DE', 'Buffalo Bills', 4),
(69, 'Reid Ferguson', 'LS', 'Buffalo Bills', 4),
(41, 'Reggie Gilliam', 'RB', 'Buffalo Bills', 4),
(3, 'Damar Hamlin', 'DB', 'Buffalo Bills', 4),
(13, 'Mack Hollins', 'WR', 'Buffalo Bills', 4),
(46, 'JaMarcus Ingram', 'DB', 'Buffalo Bills', 4),
(98, 'Austin Johnson', 'DT', 'Buffalo Bills', 4),
(7, 'Taron Johnson', 'DB', 'Buffalo Bills', 4),
(26, 'Ty Johnson', 'RB', 'Buffalo Bills', 4),
(92, 'DaQuan Jones', 'DT', 'Buffalo Bills', 4),
(86, 'Dalton Kincaid', 'TE', 'Buffalo Bills', 4),
(88, 'Dawson Knox', 'TE', 'Buffalo Bills', 4),
(39, 'Cameron Lewis', 'DB', 'Buffalo Bills', 4),
(97, 'Zion Logue', 'DT', 'Buffalo Bills', 4),
(8, 'Sam Martin', 'P', 'Buffalo Bills', 4),
(66, 'Connor McGovern', 'OG', 'Buffalo Bills', 4),
(40, 'Von Miller', 'LB', 'Buffalo Bills', 4),
(85, 'Quintin Morris', 'TE', 'Buffalo Bills', 4),
(32, 'Nicholas Morrow', 'LB', 'Buffalo Bills', 4),
(91, 'Ed Oliver', 'DT', 'Buffalo Bills', 4),
(9, 'Taylor Rapp', 'DB', 'Buffalo Bills', 4),
(50, 'Gregory Rousseau', 'DE', 'Buffalo Bills', 4),
(1, 'Curtis Samuel', 'WR', 'Buffalo Bills', 4),
(10, 'Khalil Shakir', 'WR', 'Buffalo Bills', 4),
(94, 'Dawuane Smoot', 'DE', 'Buffalo Bills', 4),
(56, 'Javon Solomon', 'DE', 'Buffalo Bills', 4),
(54, 'Baylon Spector', 'LB', 'Buffalo Bills', 4),
(99, 'Casey Toohill', 'DE', 'Buffalo Bills', 4),
(64, 'OCyrus Torrence', 'OG', 'Buffalo Bills', 4),
(11, 'Mitchell Trubisky', 'QB', 'Buffalo Bills', 4),
(48, 'Edefuan Ulofoshio', 'LB', 'Buffalo Bills', 4),
(74, 'Ryan Van Demark', 'OT', 'Buffalo Bills', 4),
(62, 'Sedrick Van Pran', 'C', 'Buffalo Bills', 4),
(89, 'Jalen Virgil', 'WR', 'Buffalo Bills', 4),
(42, 'Dorian Williams', 'LB', 'Buffalo Bills', 4),
(27, 'Shemar Bartholomew', 'DB', 'Carolina Panthers', 5),
(3, 'Raheem Blackshear', 'RB', 'Carolina Panthers', 5),
(53, 'Claudin Cherelus', 'LB', 'Carolina Panthers', 5),
(70, 'Brady Christensen', 'OG', 'Carolina Panthers', 5),
(7, 'Jadeveon Clowney', 'LB', 'Carolina Panthers', 5),
(18, 'Jalen Coker', 'WR', 'Carolina Panthers', 5),
(14, 'Andy Dalton', 'QB', 'Carolina Panthers', 5),
(79, 'Ikem Ekwonu', 'OT', 'Carolina Panthers', 5),
(31, 'Caleb Farley', 'DB', 'Carolina Panthers', 5),
(42, 'Sam Franklin', 'DB', 'Carolina Panthers', 5),
(84, 'Feleipe Franks', 'TE', 'Carolina Panthers', 5),
(45, 'Cam Gill', 'LB', 'Carolina Panthers', 5),
(40, 'Charles Harris', 'LB', 'Carolina Panthers', 5),
(92, 'Jonathan Harris', 'DE', 'Carolina Panthers', 5),
(10, 'Johnny Hekker', 'P', 'Carolina Panthers', 5),
(8, 'Jaycee Horn', 'DB', 'Carolina Panthers', 5),
(30, 'Chuba Hubbard', 'RB', 'Carolina Panthers', 5),
(50, 'Robert Hunt', 'OG', 'Carolina Panthers', 5),
(48, 'Thomas Incoom', 'LB', 'Carolina Panthers', 5),
(23, 'Dane Jackson', 'DB', 'Carolina Panthers', 5),
(2, 'Michael Jackson', 'DB', 'Carolina Panthers', 5),
(44, 'J.J. Jansen', 'LS', 'Carolina Panthers', 5),
(47, 'Josey Jewell', 'LB', 'Carolina Panthers', 5),
(52, 'D.J. Johnson', 'LB', 'Carolina Panthers', 5),
(32, 'Lonnie Johnson', 'DB', 'Carolina Panthers', 5),
(61, 'Jarrett Kingston', 'OG', 'Carolina Panthers', 5),
(17, 'Xavier Legette', 'WR', 'Carolina Panthers', 5),
(68, 'Damien Lewis', 'OG', 'Carolina Panthers', 5),
(81, 'Jordan Matthews', 'WR', 'Carolina Panthers', 5),
(64, 'Cade Mays', 'OG', 'Carolina Panthers', 5),
(15, 'Jonathan Mingo', 'WR', 'Carolina Panthers', 5),
(83, 'David Moore', 'WR', 'Carolina Panthers', 5),
(72, 'Taylor Moton', 'OT', 'Carolina Panthers', 5),
(77, 'Yosuah Nijman', 'OT', 'Carolina Panthers', 5),
(4, 'Eddy Pineiro', 'K', 'Carolina Panthers', 5),
(93, 'LaBryan Ray', 'DE', 'Carolina Panthers', 5),
(49, 'Jon Rhattigan', 'LB', 'Carolina Panthers', 5),
(36, 'Demani Richardson', 'DB', 'Carolina Panthers', 5),
(94, 'AShawn Robinson', 'DE', 'Carolina Panthers', 5),
(22, 'Jammie Robinson', 'DB', 'Carolina Panthers', 5),
(0, 'JaTavion Sanders', 'TE', 'Carolina Panthers', 5),
(6, 'Miles Sanders', 'RB', 'Carolina Panthers', 5),
(26, 'Chau Smith-Wade', 'DB', 'Carolina Panthers', 5),
(80, 'Ian Thomas', 'TE', 'Carolina Panthers', 5),
(12, 'Deven Thompkins', 'WR', 'Carolina Panthers', 5),
(91, 'Nick Thurman', 'DT', 'Carolina Panthers', 5),
(82, 'Tommy Tremble', 'TE', 'Carolina Panthers', 5),
(99, 'Shy Tuttle', 'DT', 'Carolina Panthers', 5),
(56, 'Trevin Wallace', 'LB', 'Carolina Panthers', 5),
(75, 'DeShawn Williams', 'DT', 'Carolina Panthers', 5),
(41, 'Jacoby Windmon', 'LB', 'Carolina Panthers', 5),
(25, 'Xavier Woods', 'DB', 'Carolina Panthers', 5),
(9, 'Bryce Young', 'QB', 'Carolina Panthers', 5),
(62, 'Chandler Zavala', 'OG', 'Carolina Panthers', 5),
(13, 'Keenan Allen', 'WR', 'Chicago Bears', 6),
(72, 'Kiran Amegadjie', 'OT', 'Chicago Bears', 6),
(17, 'Tyson Bagent', 'QB', 'Chicago Bears', 6),
(97, 'Andrew Billings', 'DT', 'Chicago Bears', 6),
(39, 'Josh Blackwell', 'DB', 'Chicago Bears', 6),
(94, 'Austin Booker', 'DE', 'Chicago Bears', 6),
(75, 'Larry Borom', 'OT', 'Chicago Bears', 6),
(9, 'Jaquan Brisker', 'DB', 'Chicago Bears', 6),
(31, 'Kevin Byard', 'DB', 'Chicago Bears', 6),
(11, 'DeAndre Carter', 'WR', 'Chicago Bears', 6),
(93, 'Byron Cowart', 'DT', 'Chicago Bears', 6),
(73, 'Jake Curhan', 'OT', 'Chicago Bears', 6),
(46, 'Scott Daly', 'LS', 'Chicago Bears', 6),
(64, 'Nate Davis', 'OG', 'Chicago Bears', 6),
(99, 'Gervon Dexter', 'DT', 'Chicago Bears', 6),
(49, 'Tremaine Edmunds', 'LB', 'Chicago Bears', 6),
(53, 'T.J. Edwards', 'LB', 'Chicago Bears', 6),
(14, 'Gerald Everett', 'TE', 'Chicago Bears', 6),
(6, 'Kyler Gordon', 'DB', 'Chicago Bears', 6),
(92, 'Daniel Hardy', 'LB', 'Chicago Bears', 6),
(24, 'Khalil Herbert', 'RB', 'Chicago Bears', 6),
(22, 'Elijah Hicks', 'DB', 'Chicago Bears', 6),
(20, 'Travis Homer', 'RB', 'Chicago Bears', 6),
(76, 'Teven Jenkins', 'OG', 'Chicago Bears', 6),
(1, 'Jaylon Johnson', 'DB', 'Chicago Bears', 6),
(23, 'Roschon Johnson', 'RB', 'Chicago Bears', 6),
(70, 'Braxton Jones', 'OT', 'Chicago Bears', 6),
(21, 'Jaylon Jones', 'DB', 'Chicago Bears', 6),
(85, 'Cole Kmet', 'TE', 'Chicago Bears', 6),
(68, 'Doug Kramer', 'C', 'Chicago Bears', 6),
(84, 'Marcedes Lewis', 'TE', 'Chicago Bears', 6),
(55, 'Jacob Martin', 'DE', 'Chicago Bears', 6),
(2, 'D.J. Moore', 'WR', 'Chicago Bears', 6),
(15, 'Rome Odunze', 'WR', 'Chicago Bears', 6),
(45, 'Amen Ogbongbemiga', 'LB', 'Chicago Bears', 6),
(36, 'Jonathan Owens', 'DB', 'Chicago Bears', 6),
(96, 'Zacch Pickens', 'DT', 'Chicago Bears', 6),
(79, 'Matt Pryor', 'OT', 'Chicago Bears', 6),
(90, 'Dominique Robinson', 'LB', 'Chicago Bears', 6),
(57, 'Jack Sanborn', 'LB', 'Chicago Bears', 6),
(8, 'Cairo Santos', 'K', 'Chicago Bears', 6),
(10, 'Tyler Scott', 'WR', 'Chicago Bears', 6),
(44, 'Noah Sewell', 'LB', 'Chicago Bears', 6),
(65, 'Coleman Shelton', 'C', 'Chicago Bears', 6),
(32, 'Terell Smith', 'DB', 'Chicago Bears', 6),
(29, 'Tyrique Stevenson', 'DB', 'Chicago Bears', 6),
(46, 'Reddy Steward', 'DB', 'Chicago Bears', 6),
(98, 'Montez Sweat', 'DE', 'Chicago Bears', 6),
(4, 'DAndre Swift', 'RB', 'Chicago Bears', 6),
(52, 'Darrell Taylor', 'LB', 'Chicago Bears', 6),
(19, 'Tory Taylor', 'P', 'Chicago Bears', 6),
(95, 'DeMarcus Walker', 'DE', 'Chicago Bears', 6),
(18, 'Caleb Williams', 'QB', 'Chicago Bears', 6),
(91, 'Chris Williams', 'DT', 'Chicago Bears', 6),
(58, 'Darnell Wright', 'OT', 'Chicago Bears', 6),
(48, 'Cal Adomitis', 'LS', 'Cincinnati Bengals', 7),
(83, 'Erick All', 'TE', 'Cincinnati Bengals', 7),
(26, 'Tycen Anderson', 'DB', 'Cincinnati Bengals', 7),
(33, 'Daijahn Anthony', 'DB', 'Cincinnati Bengals', 7),
(49, 'Joe Bachie', 'LB', 'Cincinnati Bengals', 7),
(27, 'Jordan Battle', 'DB', 'Cincinnati Bengals', 7),
(24, 'Vonn Bell', 'DB', 'Cincinnati Bengals', 7),
(30, 'Chase Brown', 'RB', 'Cincinnati Bengals', 7),
(75, 'Orlando Brown', 'OT', 'Cincinnati Bengals', 7),
(6, 'Jake Browning', 'QB', 'Cincinnati Bengals', 7),
(9, 'Joe Burrow', 'QB', 'Cincinnati Bengals', 7),
(81, 'Jermaine Burton', 'WR', 'Cincinnati Bengals', 7),
(65, 'Alex Cappa', 'OG', 'Cincinnati Bengals', 7),
(1, 'JaMarr Chase', 'WR', 'Cincinnati Bengals', 7),
(76, 'Devin Cochran', 'OT', 'Cincinnati Bengals', 7),
(59, 'Akeem Davis', 'LB', 'Cincinnati Bengals', 7),
(61, 'Cody Ford', 'OG', 'Cincinnati Bengals', 7),
(88, 'Mike Gesicki', 'TE', 'Cincinnati Bengals', 7),
(91, 'Trey Hendrickson', 'DE', 'Cincinnati Bengals', 7),
(5, 'Tee Higgins', 'WR', 'Cincinnati Bengals', 7),
(92, 'B.J. Hill', 'DT', 'Cincinnati Bengals', 7),
(21, 'Mike Hilton', 'DB', 'Cincinnati Bengals', 7),
(94, 'Sam Hubbard', 'DE', 'Cincinnati Bengals', 7),
(87, 'Tanner Hudson', 'TE', 'Cincinnati Bengals', 7),
(80, 'Andrei Iosivas', 'WR', 'Cincinnati Bengals', 7),
(16, 'Trenton Irwin', 'WR', 'Cincinnati Bengals', 7),
(38, 'DJ Ivey', 'DB', 'Cincinnati Bengals', 7),
(93, 'McKinnley Jackson', 'DT', 'Cincinnati Bengals', 7),
(90, 'Kris Jenkins', 'DT', 'Cincinnati Bengals', 7),
(52, 'Cedric Johnson', 'DE', 'Cincinnati Bengals', 7),
(15, 'Charlie Jones', 'WR', 'Cincinnati Bengals', 7),
(64, 'Ted Karras', 'C', 'Cincinnati Bengals', 7),
(62, 'Matthew Lee', 'C', 'Cincinnati Bengals', 7),
(84, 'Tanner McLachlan', 'TE', 'Cincinnati Bengals', 7),
(2, 'Evan McPherson', 'K', 'Cincinnati Bengals', 7),
(36, 'Kendall Milton', 'RB', 'Cincinnati Bengals', 7),
(71, 'Amarius Mims', 'OT', 'Cincinnati Bengals', 7),
(31, 'Zack Moss', 'RB', 'Cincinnati Bengals', 7),
(99, 'Myles Murphy', 'DE', 'Cincinnati Bengals', 7),
(28, 'Josh Newton', 'DB', 'Cincinnati Bengals', 7),
(45, 'Maema Njongmeta', 'LB', 'Cincinnati Bengals', 7),
(58, 'Joseph Ossai', 'DE', 'Cincinnati Bengals', 7),
(57, 'Germaine Pratt', 'LB', 'Cincinnati Bengals', 7),
(19, 'Kendric Pryor', 'WR', 'Cincinnati Bengals', 7),
(98, 'Sheldon Rankins', 'DT', 'Cincinnati Bengals', 7),
(8, 'Ryan Rehkow', 'P', 'Cincinnati Bengals', 7),
(89, 'Drew Sample', 'TE', 'Cincinnati Bengals', 7),
(22, 'Geno Stone', 'DB', 'Cincinnati Bengals', 7),
(73, 'Andrew Stueber', 'OT', 'Cincinnati Bengals', 7),
(29, 'Cam Taylor-Britt', 'DB', 'Cincinnati Bengals', 7),
(97, 'Jay Tufele', 'DT', 'Cincinnati Bengals', 7),
(20, 'DJ Turner', 'DB', 'Cincinnati Bengals', 7),
(67, 'Cordell Volson', 'OG', 'Cincinnati Bengals', 7),
(32, 'Trayveon Williams', 'RB', 'Cincinnati Bengals', 7),
(55, 'Logan Wilson', 'LB', 'Cincinnati Bengals', 7),
(88, 'Jordan Akins', 'TE', 'Cleveland Browns', 8),
(37, 'DAnthony Bell', 'DB', 'Cleveland Browns', 8),
(75, 'Joel Bitonio', 'OG', 'Cleveland Browns', 8),
(13, 'Corey Bojorquez', 'P', 'Cleveland Browns', 8),
(30, 'Devin Bush', 'LB', 'Cleveland Browns', 8),
(24, 'Nick Chubb', 'RB', 'Cleveland Browns', 8),
(78, 'Jack Conklin', 'OT', 'Cleveland Browns', 8),
(16, 'Jaelon Darden', 'WR', 'Cleveland Browns', 8),
(9, 'Grant Delpit', 'DB', 'Cleveland Browns', 8),
(43, 'Mohamoud Diabate', 'LB', 'Cleveland Browns', 8),
(68, 'Michael Dunn', 'OG', 'Cleveland Browns', 8),
(23, 'Martin Emerson', 'DB', 'Cleveland Browns', 8),
(34, 'Jerome Ford', 'RB', 'Cleveland Browns', 8),
(31, 'Mike Ford', 'DB', 'Cleveland Browns', 8),
(27, 'DOnta Foreman', 'RB', 'Cleveland Browns', 8),
(95, 'Myles Garrett', 'DE', 'Cleveland Browns', 8),
(51, 'Michael Hall', 'DT', 'Cleveland Browns', 8),
(93, 'Shelby Harris', 'DT', 'Cleveland Browns', 8),
(33, 'Ronnie Hickman', 'DB', 'Cleveland Browns', 8),
(58, 'Jordan Hicks', 'LB', 'Cleveland Browns', 8),
(7, 'Dustin Hopkins', 'K', 'Cleveland Browns', 8),
(39, 'Khaleke Hudson', 'LB', 'Cleveland Browns', 8),
(90, 'Maurice Hurst', 'DT', 'Cleveland Browns', 8),
(65, 'Germain Ifedi', 'OG', 'Cleveland Browns', 8),
(72, 'Quinton Jefferson', 'DT', 'Cleveland Browns', 8),
(3, 'Jerry Jeudy', 'WR', 'Cleveland Browns', 8),
(79, 'Dawand Jones', 'OT', 'Cleveland Browns', 8),
(92, 'Sam Kamara', 'DE', 'Cleveland Browns', 8),
(57, 'Isaiah McGuire', 'DE', 'Cleveland Browns', 8),
(12, 'Rodney McLeod', 'DB', 'Cleveland Browns', 8),
(29, 'Cameron Mitchell', 'DB', 'Cleveland Browns', 8),
(8, 'Elijah Moore', 'WR', 'Cleveland Browns', 8),
(0, 'Greg Newsome', 'DB', 'Cleveland Browns', 8),
(85, 'David Njoku', 'TE', 'Cleveland Browns', 8),
(54, 'Ogbonnia Okoronkwo', 'DE', 'Cleveland Browns', 8),
(55, 'Ethan Pocic', 'C', 'Cleveland Browns', 8),
(59, 'Winston Reid', 'LB', 'Cleveland Browns', 8),
(99, 'ZaDarius Smith', 'DE', 'Cleveland Browns', 8),
(20, 'Pierre Strong', 'RB', 'Cleveland Browns', 8),
(50, 'Rex Sunahara', 'LS', 'Cleveland Browns', 8),
(84, 'Geoff Swaim', 'TE', 'Cleveland Browns', 8),
(77, 'Wyatt Teller', 'OG', 'Cleveland Browns', 8),
(17, 'Dorian Thompson-Robinson', 'QB', 'Cleveland Browns', 8),
(1, 'Juan Thornhill', 'DB', 'Cleveland Browns', 8),
(80, 'Jamari Thrash', 'WR', 'Cleveland Browns', 8),
(19, 'Cedric Tillman', 'WR', 'Cleveland Browns', 8),
(94, 'Dalvin Tomlinson', 'DT', 'Cleveland Browns', 8),
(21, 'Denzel Ward', 'DB', 'Cleveland Browns', 8),
(40, 'Nathaniel Watson', 'LB', 'Cleveland Browns', 8),
(71, 'Jedrick Wills', 'OT', 'Cleveland Browns', 8),
(5, 'Jameis Winston', 'QB', 'Cleveland Browns', 8),
(2, 'Bailey Zappe', 'QB', 'Cleveland Browns', 8),
(70, 'Zak Zinter', 'OG', 'Cleveland Browns', 8),
(5, 'Bryan Anger', 'P', 'Dallas Cowboys', 9),
(17, 'Brandon Aubrey', 'K', 'Dallas Cowboys', 9),
(66, 'T.J. Bass', 'OG', 'Dallas Cowboys', 9),
(56, 'Cooper Beebe', 'OG', 'Dallas Cowboys', 9),
(14, 'Markquese Bell', 'DB', 'Dallas Cowboys', 9),
(26, 'DaRon Bland', 'DB', 'Dallas Cowboys', 9),
(25, 'Andrew Booth', 'DB', 'Dallas Cowboys', 9),
(83, 'Jalen Brooks', 'WR', 'Dallas Cowboys', 9),
(31, 'Josh Butler', 'DB', 'Dallas Cowboys', 9),
(21, 'Caelen Carson', 'DB', 'Dallas Cowboys', 9),
(18, 'Damone Clark', 'LB', 'Dallas Cowboys', 9),
(20, 'Dalvin Cook', 'RB', 'Dallas Cowboys', 9),
(7, 'Trevon Diggs', 'DB', 'Dallas Cowboys', 9),
(23, 'Rico Dowdle', 'RB', 'Dallas Cowboys', 9),
(15, 'Ezekiel Elliott', 'RB', 'Dallas Cowboys', 9),
(87, 'Jake Ferguson', 'TE', 'Dallas Cowboys', 9),
(80, 'Ryan Flournoy', 'WR', 'Dallas Cowboys', 9),
(99, 'Chauncey Golston', 'DE', 'Dallas Cowboys', 9),
(29, 'C.J. Goodwin', 'DB', 'Dallas Cowboys', 9),
(60, 'Tyler Guyton', 'OT', 'Dallas Cowboys', 9),
(52, 'K.J. Henry', 'DE', 'Dallas Cowboys', 9),
(67, 'Brock Hoffman', 'C', 'Dallas Cowboys', 9),
(28, 'Malik Hooker', 'DB', 'Dallas Cowboys', 9),
(57, 'Buddy Johnson', 'LB', 'Dallas Cowboys', 9),
(93, 'Linval Joseph', 'DT', 'Dallas Cowboys', 9),
(50, 'Eric Kendricks', 'LB', 'Dallas Cowboys', 9),
(88, 'CeeDee Lamb', 'WR', 'Dallas Cowboys', 9),
(19, 'Trey Lance', 'QB', 'Dallas Cowboys', 9),
(55, 'Carl Lawson', 'DE', 'Dallas Cowboys', 9),
(2, 'Jourdan Lewis', 'DB', 'Dallas Cowboys', 9),
(35, 'Marist Liufau', 'LB', 'Dallas Cowboys', 9),
(40, 'Hunter Luepke', 'RB', 'Dallas Cowboys', 9),
(70, 'Zack Martin', 'OG', 'Dallas Cowboys', 9),
(24, 'Israel Mukuamu', 'DB', 'Dallas Cowboys', 9),
(97, 'Osa Odighizuwa', 'DT', 'Dallas Cowboys', 9),
(13, 'DeMarvion Overshown', 'LB', 'Dallas Cowboys', 9),
(11, 'Micah Parsons', 'LB', 'Dallas Cowboys', 9),
(4, 'Dak Prescott', 'QB', 'Dallas Cowboys', 9),
(76, 'Asim Richards', 'OT', 'Dallas Cowboys', 9),
(10, 'Cooper Rush', 'QB', 'Dallas Cowboys', 9),
(86, 'Luke Schoonmaker', 'TE', 'Dallas Cowboys', 9),
(44, 'Trent Sieg', 'LS', 'Dallas Cowboys', 9),
(58, 'Mazi Smith', 'DT', 'Dallas Cowboys', 9),
(73, 'Tyler Smith', 'OT', 'Dallas Cowboys', 9),
(89, 'Brevyn Spann-Ford', 'TE', 'Dallas Cowboys', 9),
(78, 'Terence Steele', 'OT', 'Dallas Cowboys', 9),
(30, 'Juanyeh Thomas', 'DB', 'Dallas Cowboys', 9),
(1, 'Jalen Tolbert', 'WR', 'Dallas Cowboys', 9),
(9, 'KaVontae Turpin', 'WR', 'Dallas Cowboys', 9),
(42, 'Deuce Vaughn', 'RB', 'Dallas Cowboys', 9),
(41, 'Nick Vigil', 'LB', 'Dallas Cowboys', 9),
(79, 'Matt Waletzko', 'OT', 'Dallas Cowboys', 9),
(92, 'Carlos Watkins', 'DE', 'Dallas Cowboys', 9),
(91, 'Tyrus Wheat', 'DE', 'Dallas Cowboys', 9),
(6, 'Donovan Wilson', 'DB', 'Dallas Cowboys', 9),
(31, 'Kris Abrams-Draine', 'DB', 'Denver Broncos', 10),
(45, 'Nate Adkins', 'TE', 'Denver Broncos', 10),
(12, 'Kwon Alexander', 'LB', 'Denver Broncos', 10),
(99, 'Zach Allen', 'DE', 'Denver Broncos', 10),
(56, 'Levelle Bailey', 'LB', 'Denver Broncos', 10),
(55, 'Cody Barton', 'LB', 'Denver Broncos', 10),
(72, 'Garett Bolles', 'OT', 'Denver Broncos', 10),
(15, 'Nik Bonitto', 'LB', 'Denver Broncos', 10),
(5, 'Baron Browning', 'LB', 'Denver Broncos', 10),
(20, 'Michael Burton', 'RB', 'Denver Broncos', 10),
(0, 'Jonathon Cooper', 'LB', 'Denver Broncos', 10),
(73, 'Frank Crum', 'OT', 'Denver Broncos', 10),
(9, 'Riley Dixon', 'P', 'Denver Broncos', 10),
(80, 'Greg Dulcich', 'TE', 'Denver Broncos', 10),
(52, 'Jonah Elliss', 'LB', 'Denver Broncos', 10),
(23, 'Audric Estime', 'RB', 'Denver Broncos', 10),
(54, 'Alex Forsyth', 'C', 'Denver Broncos', 10),
(48, 'MItchell Fraboni', 'LS', 'Denver Broncos', 10),
(16, 'Troy Franklin', 'WR', 'Denver Broncos', 10),
(98, 'John Franklin-Myers', 'DE', 'Denver Broncos', 10),
(84, 'LilJordan Humphrey', 'WR', 'Denver Broncos', 10),
(94, 'Jordan Jackson', 'DT', 'Denver Broncos', 10),
(22, 'Brandon Jones', 'DB', 'Denver Broncos', 10),
(93, 'D.J. Jones', 'DT', 'Denver Broncos', 10),
(26, 'Devon Key', 'DB', 'Denver Broncos', 10),
(85, 'Lucas Krull', 'TE', 'Denver Broncos', 10),
(6, 'P.J. Locke', 'DB', 'Denver Broncos', 10),
(3, 'Wil Lutz', 'K', 'Denver Broncos', 10),
(27, 'Damarri Mathis', 'DB', 'Denver Broncos', 10),
(69, 'Mike McGlinchey', 'OT', 'Denver Broncos', 10),
(38, 'Jaleel McLaughlin', 'RB', 'Denver Broncos', 10),
(29, 'JaQuan McMillian', 'DB', 'Denver Broncos', 10),
(77, 'Quinn Meinerz', 'OG', 'Denver Broncos', 10),
(19, 'Marvin Mims', 'WR', 'Denver Broncos', 10),
(21, 'Riley Moss', 'DB', 'Denver Broncos', 10),
(10, 'Bo Nix', 'QB', 'Denver Broncos', 10),
(63, 'Alex Palczewski', 'OT', 'Denver Broncos', 10),
(79, 'Matt Peart', 'OT', 'Denver Broncos', 10),
(74, 'Ben Powers', 'OG', 'Denver Broncos', 10),
(97, 'Malcolm Roach', 'DT', 'Denver Broncos', 10),
(34, 'JL Skinner', 'DB', 'Denver Broncos', 10),
(43, 'Keidron Smith', 'DB', 'Denver Broncos', 10),
(1, 'Tremon Smith', 'DB', 'Denver Broncos', 10),
(8, 'Jarrett Stidham', 'QB', 'Denver Broncos', 10),
(40, 'Justin Strnad', 'LB', 'Denver Broncos', 10),
(2, 'Patrick Surtain', 'DB', 'Denver Broncos', 10),
(14, 'Courtland Sutton', 'WR', 'Denver Broncos', 10),
(76, 'Calvin Throckmorton', 'OG', 'Denver Broncos', 10),
(92, 'Dondrea Tillman', 'LB', 'Denver Broncos', 10),
(82, 'Adam Trautman', 'TE', 'Denver Broncos', 10),
(96, 'Eyioma Uwazurike', 'DT', 'Denver Broncos', 10),
(17, 'Devaughn Vele', 'WR', 'Denver Broncos', 10),
(39, 'Levi Wallace', 'DB', 'Denver Broncos', 10),
(33, 'Javonte Williams', 'RB', 'Denver Broncos', 10),
(4, 'Zach Wilson', 'QB', 'Denver Broncos', 10),
(34, 'Alex Anzalone', 'LB', 'Detroit Lions', 11),
(0, 'Terrion Arnold', 'DB', 'Detroit Lions', 11),
(74, 'Kayode Awosika', 'OG', 'Detroit Lions', 11),
(39, 'Jake Bates', 'K', 'Detroit Lions', 11),
(59, 'Abraham Beauplan', 'LB', 'Detroit Lions', 11),
(32, 'Brian Branch', 'DB', 'Detroit Lions', 11),
(46, 'Jack Campbell', 'LB', 'Detroit Lions', 11),
(23, 'Carlton Davis', 'DB', 'Detroit Lions', 11),
(68, 'Taylor Decker', 'OT', 'Detroit Lions', 11),
(30, 'Khalil Dorsey', 'DB', 'Detroit Lions', 11),
(3, 'Jack Fox', 'P', 'Detroit Lions', 11),
(26, 'Jahmyr Gibbs', 'RB', 'Detroit Lions', 11),
(60, 'Graham Glasgow', 'OG', 'Detroit Lions', 11),
(16, 'Jared Goff', 'QB', 'Detroit Lions', 11),
(49, 'Hogan Hatten', 'LS', 'Detroit Lions', 11),
(2, 'Hendon Hooker', 'QB', 'Detroit Lions', 11),
(41, 'James Houston', 'LB', 'Detroit Lions', 11),
(12, 'Brandon Joseph', 'DB', 'Detroit Lions', 11),
(31, 'Kerby Joseph', 'DB', 'Detroit Lions', 11),
(87, 'Sam LaPorta', 'TE', 'Detroit Lions', 11),
(73, 'Christian Mahogany', 'OG', 'Detroit Lions', 11),
(59, 'Giovanni Manu', 'OT', 'Detroit Lions', 11),
(54, 'Alim McNeill', 'DT', 'Detroit Lions', 11),
(5, 'David Montgomery', 'RB', 'Detroit Lions', 11),
(69, 'Al-Quadin Muhammad', 'DL', 'Detroit Lions', 11),
(51, 'Ben Niemann', 'LB', 'Detroit Lions', 11),
(62, 'Michael Niese', 'OT', 'Detroit Lions', 11),
(53, 'Trevor Nowaske', 'LB', 'Detroit Lions', 11),
(95, 'Pat OConnor', 'DE', 'Detroit Lions', 11),
(91, 'Levi Onwuzurike', 'DE', 'Detroit Lions', 11),
(93, 'Joshua Paschal', 'DE', 'Detroit Lions', 11),
(17, 'Tim Patrick', 'WR', 'Detroit Lions', 11),
(77, 'Frank Ragnow', 'C', 'Detroit Lions', 11),
(15, 'Ennis Rakestraw', 'DB', 'Detroit Lions', 11),
(11, 'Kalif Raymond', 'WR', 'Detroit Lions', 11),
(98, 'D.J. Reader', 'DT', 'Detroit Lions', 11),
(42, 'Jalen Reeves-Maybin', 'LB', 'Detroit Lions', 11),
(13, 'Craig Reynolds', 'RB', 'Detroit Lions', 11),
(21, 'Amik Robertson', 'DB', 'Detroit Lions', 11),
(8, 'Allen Robinson', 'WR', 'Detroit Lions', 11),
(44, 'Malcolm Rodriguez', 'LB', 'Detroit Lions', 11),
(58, 'Penei Sewell', 'OT', 'Detroit Lions', 11),
(70, 'Dan Skipper', 'OT', 'Detroit Lions', 11),
(90, 'Chris Smith', 'DT', 'Detroit Lions', 11),
(75, 'Colby Sorsdal', 'OT', 'Detroit Lions', 11),
(14, 'Amon-Ra St. Brown', 'WR', 'Detroit Lions', 11),
(24, 'Loren Strickland', 'DB', 'Detroit Lions', 11),
(35, 'Isaiah Thomas', 'DE', 'Detroit Lions', 11),
(33, 'Sione Vaki', 'RB', 'Detroit Lions', 11),
(29, 'Kindle Vildor', 'DB', 'Detroit Lions', 11),
(83, 'Isaiah Williams', 'WR', 'Detroit Lions', 11),
(94, 'Mekhi Wingo', 'DT', 'Detroit Lions', 11),
(89, 'Brock Wright', 'TE', 'Detroit Lions', 11),
(71, 'Kevin Zeitler', 'OG', 'Detroit Lions', 11),
(84, 'Shane Zylstra', 'TE', 'Detroit Lions', 11),
(23, 'Jaire Alexander', 'DB', 'Green Bay Packers', 12),
(39, 'Zayne Anderson', 'DB', 'Green Bay Packers', 12),
(26, 'Corey Ballentine', 'DB', 'Green Bay Packers', 12),
(30, 'Christopher Brooks', 'RB', 'Green Bay Packers', 12),
(94, 'Karl Brooks', 'DE', 'Green Bay Packers', 12),
(20, 'Javon Bullard', 'DB', 'Green Bay Packers', 12),
(97, 'Kenny Clark', 'DT', 'Green Bay Packers', 12),
(56, 'Edgerrin Cooper', 'LB', 'Green Bay Packers', 12),
(57, 'Brenton Cox', 'LB', 'Green Bay Packers', 12),
(73, 'Andre Dillard', 'OT', 'Green Bay Packers', 12),
(87, 'Romeo Doubs', 'WR', 'Green Bay Packers', 12),
(55, 'Kingsley Enagbare', 'LB', 'Green Bay Packers', 12),
(86, 'John FitzPatrick', 'TE', 'Green Bay Packers', 12),
(52, 'Rashan Gary', 'LB', 'Green Bay Packers', 12),
(79, 'Travis Glover', 'OT', 'Green Bay Packers', 12),
(36, 'Kamal Hadden', 'DB', 'Green Bay Packers', 12),
(18, 'Malik Heath', 'WR', 'Green Bay Packers', 12),
(59, 'TyRon Hopper', 'LB', 'Green Bay Packers', 12),
(8, 'Josh Jacobs', 'RB', 'Green Bay Packers', 12),
(74, 'Elgton Jenkins', 'OG', 'Green Bay Packers', 12),
(85, 'Tucker Kraft', 'TE', 'Green Bay Packers', 12),
(10, 'Jordan Love', 'QB', 'Green Bay Packers', 12),
(58, 'Isaiah McDuffie', 'LB', 'Green Bay Packers', 12),
(29, 'Xavier McKinney', 'DB', 'Green Bay Packers', 12),
(17, 'Brandon McManus', 'K', 'Green Bay Packers', 12),
(80, 'Bo Melton', 'WR', 'Green Bay Packers', 12),
(62, 'Jacob Monk', 'C', 'Green Bay Packers', 12),
(77, 'Jordan Morgan', 'OT', 'Green Bay Packers', 12),
(53, 'Arron Mosby', 'LB', 'Green Bay Packers', 12),
(71, 'Josh Myers', 'C', 'Green Bay Packers', 12),
(25, 'Keisean Nixon', 'DB', 'Green Bay Packers', 12),
(27, 'Kitan Oladapo', 'DB', 'Green Bay Packers', 12),
(42, 'Matt Orzech', 'LS', 'Green Bay Packers', 12),
(11, 'Jayden Reed', 'WR', 'Green Bay Packers', 12),
(75, 'Sean Rhyan', 'OG', 'Green Bay Packers', 12),
(89, 'Ben Sims', 'TE', 'Green Bay Packers', 12),
(93, 'Tedarrell Slaton', 'DT', 'Green Bay Packers', 12),
(91, 'Preston Smith', 'LB', 'Green Bay Packers', 12),
(21, 'Eric Stokes', 'DB', 'Green Bay Packers', 12),
(76, 'Kadeem Telfort', 'OT', 'Green Bay Packers', 12),
(50, 'Zach Tom', 'C', 'Green Bay Packers', 12),
(24, 'Carrington Valentine', 'DB', 'Green Bay Packers', 12),
(90, 'Lukas Van Ness', 'LB', 'Green Bay Packers', 12),
(7, 'Quay Walker', 'LB', 'Green Bay Packers', 12),
(63, 'Rasheed Walker', 'OT', 'Green Bay Packers', 12),
(9, 'Christian Watson', 'WR', 'Green Bay Packers', 12),
(19, 'Daniel Whelan', 'P', 'Green Bay Packers', 12),
(13, 'Dontayvion Wicks', 'WR', 'Green Bay Packers', 12),
(33, 'Evan Williams', 'DB', 'Green Bay Packers', 12),
(2, 'Malik Willis', 'QB', 'Green Bay Packers', 12),
(31, 'Emanuel Wilson', 'RB', 'Green Bay Packers', 12),
(45, 'Eric Wilson', 'LB', 'Green Bay Packers', 12),
(96, 'Colby Wooden', 'DE', 'Green Bay Packers', 12),
(95, 'Devonte Wyatt', 'DT', 'Green Bay Packers', 12),
(0, 'Azeez Al-Shaair', 'LB', 'Houston Texans', 13),
(51, 'Will Anderson', 'DE', 'Houston Texans', 13),
(96, 'Denico Autry', 'DE', 'Houston Texans', 13),
(95, 'Derek Barnett', 'DE', 'Houston Texans', 13),
(17, 'Kris Boyd', 'DB', 'Houston Texans', 13),
(64, 'Nick Broeker', 'OG', 'Houston Texans', 13),
(27, 'Myles Bryant', 'DB', 'Houston Texans', 13),
(21, 'Calen Bullock', 'DB', 'Houston Texans', 13),
(94, 'Khalil Davis', 'DT', 'Houston Texans', 13),
(3, 'Nathaniel Dell', 'WR', 'Houston Texans', 13),
(15, 'Kaimi Fairbairn', 'K', 'Houston Texans', 13),
(91, 'Folorunso Fatukasi', 'DT', 'Houston Texans', 13),
(57, 'Blake Fisher', 'OT', 'Houston Texans', 13),
(53, 'Kendrick Green', 'C', 'Houston Texans', 13),
(76, 'Kenyon Green', 'OG', 'Houston Texans', 13),
(35, 'Jake Hansen', 'LB', 'Houston Texans', 13),
(43, 'Neville Hewitt', 'LB', 'Houston Texans', 13),
(56, 'Jamal Hill', 'LB', 'Houston Texans', 13),
(93, 'Kurt Hinish', 'DT', 'Houston Texans', 13),
(32, 'Kadar Hollman', 'DB', 'Houston Texans', 13),
(92, 'Dylan Horton', 'DE', 'Houston Texans', 13),
(71, 'Tytus Howard', 'OT', 'Houston Texans', 13),
(55, 'Danielle Hunter', 'DE', 'Houston Texans', 13),
(19, 'Xavier Hutchinson', 'WR', 'Houston Texans', 13),
(4, 'Kamari Lassiter', 'DB', 'Houston Texans', 13),
(69, 'Shaquille Mason', 'OG', 'Houston Texans', 13),
(8, 'John Metchie', 'WR', 'Houston Texans', 13),
(10, 'Davis Mills', 'QB', 'Houston Texans', 13),
(28, 'Joe Mixon', 'RB', 'Houston Texans', 13),
(23, 'Eric Murray', 'DB', 'Houston Texans', 13),
(33, 'Dare Ogunbowale', 'RB', 'Houston Texans', 13),
(54, 'Jarrett Patterson', 'C', 'Houston Texans', 13),
(13, 'DelShawn Phillips', 'LB', 'Houston Texans', 13),
(31, 'Dameon Pierce', 'RB', 'Houston Texans', 13),
(5, 'Jalen Pitre', 'DB', 'Houston Texans', 13),
(85, 'Teagan Quitoriano', 'TE', 'Houston Texans', 13),
(37, 'DAngelo Ross', 'DB', 'Houston Texans', 13),
(86, 'Dalton Schultz', 'TE', 'Houston Texans', 13),
(70, 'Juice Scruggs', 'C', 'Houston Texans', 13),
(98, 'Tim Settle', 'DT', 'Houston Texans', 13),
(82, 'Steven Sims', 'WR', 'Houston Texans', 13),
(29, 'M.J. Stewart', 'DB', 'Houston Texans', 13),
(24, 'Derek Stingley', 'DB', 'Houston Texans', 13),
(87, 'Cade Stover', 'TE', 'Houston Texans', 13),
(7, 'C.J. Stroud', 'QB', 'Houston Texans', 13),
(26, 'J.J. Taylor', 'RB', 'Houston Texans', 13),
(39, 'Henry Too Too', 'LB', 'Houston Texans', 13),
(6, 'Tommy Townsend', 'P', 'Houston Texans', 13),
(78, 'Laremy Tunsil', 'OT', 'Houston Texans', 13),
(20, 'Jimmie Ward', 'DB', 'Houston Texans', 13),
(46, 'Jonathan Weeks', 'LS', 'Houston Texans', 13),
(45, 'Devin White', 'LB', 'Houston Texans', 13),
(2, 'Robert Woods', 'WR', 'Houston Texans', 13),
(95, 'Adetomiwa Adebawore', 'DT', 'Indianapolis Colts', 14),
(81, 'Mo Alie-Cox', 'TE', 'Indianapolis Colts', 14),
(92, 'Genard Avery', 'DE', 'Indianapolis Colts', 14),
(32, 'Julian Blackmon', 'DB', 'Indianapolis Colts', 14),
(60, 'Tanor Bortolini', 'OG', 'Indianapolis Colts', 14),
(96, 'Taven Bryan', 'DT', 'Indianapolis Colts', 14),
(99, 'DeForest Buckner', 'DT', 'Indianapolis Colts', 14),
(20, 'Nick Cross', 'DB', 'Indianapolis Colts', 14),
(98, 'Raekwon Davis', 'DT', 'Indianapolis Colts', 14),
(1, 'Josh Downs', 'WR', 'Indianapolis Colts', 14),
(16, 'Ashton Dulin', 'WR', 'Indianapolis Colts', 14),
(4, 'Sam Ehlinger', 'QB', 'Indianapolis Colts', 14),
(15, 'Joe Flacco', 'QB', 'Indianapolis Colts', 14),
(44, 'Zaire Franklin', 'LB', 'Indianapolis Colts', 14),
(73, 'Blake Freeland', 'OT', 'Indianapolis Colts', 14),
(7, 'Matt Gay', 'K', 'Indianapolis Colts', 14),
(71, 'Matt Goncalves', 'OT', 'Indianapolis Colts', 14),
(31, 'Tyler Goodson', 'RB', 'Indianapolis Colts', 14),
(93, 'Adam Gotsis', 'DT', 'Indianapolis Colts', 14),
(6, 'Anthony Gould', 'WR', 'Indianapolis Colts', 14),
(83, 'Kylen Granson', 'TE', 'Indianapolis Colts', 14),
(48, 'Ronnie Harrison', 'DB', 'Indianapolis Colts', 14),
(40, 'Jaylon Jones', 'DB', 'Indianapolis Colts', 14),
(78, 'Ryan Kelly', 'C', 'Indianapolis Colts', 14),
(35, 'Chris Lammons', 'DB', 'Indianapolis Colts', 14),
(55, 'Isaiah Land', 'DE', 'Indianapolis Colts', 14),
(97, 'Laiatu Latu', 'DE', 'Indianapolis Colts', 14),
(34, 'David Long', 'DB', 'Indianapolis Colts', 14),
(86, 'Will Mallory', 'TE', 'Indianapolis Colts', 14),
(59, 'Cameron McGrone', 'LB', 'Indianapolis Colts', 14),
(10, 'Adonai Mitchell', 'WR', 'Indianapolis Colts', 14),
(23, 'Kenny Moore', 'DB', 'Indianapolis Colts', 14),
(56, 'Quenton Nelson', 'OG', 'Indianapolis Colts', 14),
(54, 'Dayo Odeyingbo', 'DE', 'Indianapolis Colts', 14),
(85, 'Andrew Ogletree', 'TE', 'Indianapolis Colts', 14),
(50, 'Segun Olubi', 'LB', 'Indianapolis Colts', 14),
(51, 'Kwity Paye', 'DE', 'Indianapolis Colts', 14),
(14, 'Alec Pierce', 'WR', 'Indianapolis Colts', 14),
(63, 'Danny Pinter', 'C', 'Indianapolis Colts', 14),
(11, 'Michael Pittman', 'WR', 'Indianapolis Colts', 14),
(79, 'Bernhard Raimann', 'OT', 'Indianapolis Colts', 14),
(46, 'Luke Rhodes', 'LS', 'Indianapolis Colts', 14),
(5, 'Anthony Richardson', 'QB', 'Indianapolis Colts', 14),
(8, 'Rigoberto Sanchez', 'P', 'Indianapolis Colts', 14),
(27, 'Trey Sermon', 'RB', 'Indianapolis Colts', 14),
(72, 'Braden Smith', 'OT', 'Indianapolis Colts', 14),
(45, 'E.J. Speed', 'LB', 'Indianapolis Colts', 14),
(90, 'Grover Stewart', 'DT', 'Indianapolis Colts', 14),
(41, 'Grant Stuard', 'LB', 'Indianapolis Colts', 14),
(28, 'Jonathan Taylor', 'RB', 'Indianapolis Colts', 14),
(25, 'Rodney Thomas', 'DB', 'Indianapolis Colts', 14),
(68, 'Dalton Tucker', 'OG', 'Indianapolis Colts', 14),
(33, 'Sam Womack', 'DB', 'Indianapolis Colts', 14),
(56, 'Yasir Abdullah', 'LB', 'Jacksonville Jaguars', 15),
(91, 'Arik Armstead', 'DE', 'Jacksonville Jaguars', 15),
(4, 'Cartavious Bigsby', 'RB', 'Jacksonville Jaguars', 15),
(30, 'Montaric Brown', 'DB', 'Jacksonville Jaguars', 15),
(3, 'Tyson Campbell', 'DB', 'Jacksonville Jaguars', 15),
(5, 'Andre Cisco', 'DB', 'Jacksonville Jaguars', 15),
(76, 'Ezra Cleveland', 'OG', 'Jacksonville Jaguars', 15),
(59, 'Myles Cole', 'DE', 'Jacksonville Jaguars', 15),
(9, 'Logan Cooke', 'P', 'Jacksonville Jaguars', 15),
(14, 'Elijah Cooks', 'WR', 'Jacksonville Jaguars', 15),
(25, 'Ronald Darby', 'DB', 'Jacksonville Jaguars', 15),
(0, 'Gabriel Davis', 'WR', 'Jacksonville Jaguars', 15),
(81, 'Josiah Deguara', 'TE', 'Jacksonville Jaguars', 15),
(17, 'Evan Engram', 'TE', 'Jacksonville Jaguars', 15),
(1, 'Travis Etienne', 'RB', 'Jacksonville Jaguars', 15),
(89, 'Luke Farrell', 'TE', 'Jacksonville Jaguars', 15),
(79, 'Luke Fortner', 'C', 'Jacksonville Jaguars', 15),
(62, 'Javon Foster', 'OT', 'Jacksonville Jaguars', 15),
(47, 'Tashaun Gipson', 'DB', 'Jacksonville Jaguars', 15),
(52, 'Davon Hamilton', 'DT', 'Jacksonville Jaguars', 15),
(73, 'Blake Hance', 'OT', 'Jacksonville Jaguars', 15),
(77, 'Anton Harrison', 'OT', 'Jacksonville Jaguars', 15),
(41, 'Joshua Hines-Allen', 'DE', 'Jacksonville Jaguars', 15),
(75, 'Cooper Hodges', 'OT', 'Jacksonville Jaguars', 15),
(98, 'Jordan Jefferson', 'DT', 'Jacksonville Jaguars', 15),
(26, 'Antonio Johnson', 'DB', 'Jacksonville Jaguars', 15),
(57, 'Caleb Johnson', 'LB', 'Jacksonville Jaguars', 15),
(2, 'DErnest Johnson', 'RB', 'Jacksonville Jaguars', 15),
(22, 'Jarrian Jones', 'DB', 'Jacksonville Jaguars', 15),
(10, 'Mac Jones', 'QB', 'Jacksonville Jaguars', 15),
(15, 'Tim Jones', 'WR', 'Jacksonville Jaguars', 15),
(93, 'Tyler Lacy', 'DT', 'Jacksonville Jaguars', 15),
(16, 'Trevor Lawrence', 'QB', 'Jacksonville Jaguars', 15),
(99, 'Jeremiah Ledbetter', 'DT', 'Jacksonville Jaguars', 15),
(39, 'Cam Little', 'K', 'Jacksonville Jaguars', 15),
(72, 'Walker Little', 'OT', 'Jacksonville Jaguars', 15),
(33, 'Devin Lloyd', 'LB', 'Jacksonville Jaguars', 15),
(46, 'Ross Matiscik', 'LS', 'Jacksonville Jaguars', 15),
(51, 'Ventrell Miller', 'LB', 'Jacksonville Jaguars', 15),
(65, 'Mitch Morse', 'C', 'Jacksonville Jaguars', 15),
(48, 'Chad Muma', 'LB', 'Jacksonville Jaguars', 15),
(23, 'Foyesade Oluokun', 'LB', 'Jacksonville Jaguars', 15),
(90, 'Esezi Otomewo', 'DT', 'Jacksonville Jaguars', 15),
(24, 'Deantre Prince', 'DB', 'Jacksonville Jaguars', 15),
(6, 'Darnell Savage', 'DB', 'Jacksonville Jaguars', 15),
(68, 'Brandon Scherff', 'OG', 'Jacksonville Jaguars', 15),
(94, 'Maason Smith', 'DT', 'Jacksonville Jaguars', 15),
(85, 'Brenton Strange', 'TE', 'Jacksonville Jaguars', 15),
(7, 'Brian Thomas', 'WR', 'Jacksonville Jaguars', 15),
(20, 'Daniel Thomas', 'DB', 'Jacksonville Jaguars', 15),
(86, 'Austin Trammell', 'WR', 'Jacksonville Jaguars', 15),
(70, 'Cole Van Lanen', 'OG', 'Jacksonville Jaguars', 15),
(44, 'Travon Walker', 'DE', 'Jacksonville Jaguars', 15),
(11, 'Parker Washington', 'WR', 'Jacksonville Jaguars', 15),
(97, 'Felix Anudike', 'DE', 'Kansas City Chiefs', 16),
(14, 'Matt Araiza', 'P', 'Kansas City Chiefs', 16),
(32, 'Nick Bolton', 'LB', 'Kansas City Chiefs', 16),
(7, 'Harrison Butker', 'K', 'Kansas City Chiefs', 16),
(66, 'Mike Caliendo', 'OG', 'Kansas City Chiefs', 16),
(54, 'Leo Chenal', 'LB', 'Kansas City Chiefs', 16),
(48, 'Cole Christiansen', 'LB', 'Kansas City Chiefs', 16),
(43, 'Jack Cochrane', 'LB', 'Kansas City Chiefs', 16),
(27, 'Chamarri Conner', 'DB', 'Kansas City Chiefs', 16),
(6, 'Bryan Cook', 'DB', 'Kansas City Chiefs', 16),
(51, 'Mike Danna', 'DE', 'Kansas City Chiefs', 16),
(75, 'Ethan Driskell', 'OT', 'Kansas City Chiefs', 16),
(25, 'Clyde Edwards-Helaire', 'RB', 'Kansas City Chiefs', 16),
(83, 'Noah Gray', 'TE', 'Kansas City Chiefs', 16),
(61, 'C.J. Hanson', 'OG', 'Kansas City Chiefs', 16),
(17, 'Mecole Hardman', 'WR', 'Kansas City Chiefs', 16),
(88, 'Peyton Hendershot', 'TE', 'Kansas City Chiefs', 16),
(94, 'Malik Herring', 'DE', 'Kansas City Chiefs', 16),
(21, 'Jaden Hicks', 'DB', 'Kansas City Chiefs', 16),
(8, 'DeAndre Hopkins', 'WR', 'Kansas City Chiefs', 16),
(52, 'Creed Humphrey', 'C', 'Kansas City Chiefs', 16),
(29, 'Kareem Hunt', 'RB', 'Kansas City Chiefs', 16),
(13, 'Nazeeh Johnson', 'DB', 'Kansas City Chiefs', 16),
(44, 'Cam Jones', 'LB', 'Kansas City Chiefs', 16),
(95, 'Chris Jones', 'DT', 'Kansas City Chiefs', 16),
(56, 'George Karlaftis', 'DE', 'Kansas City Chiefs', 16),
(87, 'Travis Kelce', 'TE', 'Kansas City Chiefs', 16),
(15, 'Patrick Mahomes', 'QB', 'Kansas City Chiefs', 16),
(22, 'Trent McDuffie', 'DB', 'Kansas City Chiefs', 16),
(64, 'Wanya Morris', 'OT', 'Kansas City Chiefs', 16),
(91, 'Derrick Nnadi', 'DT', 'Kansas City Chiefs', 16),
(60, 'Hunter Nourzad', 'C', 'Kansas City Chiefs', 16),
(69, 'Mike Pennel', 'DT', 'Kansas City Chiefs', 16),
(34, 'Samaje Perine', 'RB', 'Kansas City Chiefs', 16),
(20, 'Justin Reid', 'DB', 'Kansas City Chiefs', 16),
(30, 'Christian Roland-Wallace', 'DB', 'Kansas City Chiefs', 16),
(65, 'Trey Smith', 'OG', 'Kansas City Chiefs', 16),
(9, 'JuJu Smith-Schuster', 'WR', 'Kansas City Chiefs', 16),
(42, 'Carson Steele', 'RB', 'Kansas City Chiefs', 16),
(76, 'Kingsley Suamataia', 'OT', 'Kansas City Chiefs', 16),
(74, 'Jawaan Taylor', 'OT', 'Kansas City Chiefs', 16),
(39, 'Keith Taylor', 'DB', 'Kansas City Chiefs', 16),
(99, 'Cameron Thomas', 'DE', 'Kansas City Chiefs', 16),
(62, 'Joe Thuney', 'OG', 'Kansas City Chiefs', 16),
(23, 'Drue Tranquill', 'LB', 'Kansas City Chiefs', 16),
(92, 'Marlon Tuipulotu', 'DT', 'Kansas City Chiefs', 16),
(0, 'Josh Uche', 'LB', 'Kansas City Chiefs', 16),
(84, 'Justin Watson', 'WR', 'Kansas City Chiefs', 16),
(11, 'Carson Wentz', 'QB', 'Kansas City Chiefs', 16),
(98, 'Tershawn Wharton', 'DT', 'Kansas City Chiefs', 16),
(2, 'Joshua Williams', 'DB', 'Kansas City Chiefs', 16),
(41, 'James Winchester', 'LS', 'Kansas City Chiefs', 16),
(1, 'Xavier Worthy', 'WR', 'Kansas City Chiefs', 16),
(76, 'Joe Alt', 'OT', 'Los Angeles Chargers', 17),
(24, 'Eli Apple', 'DB', 'Los Angeles Chargers', 17),
(35, 'Dicaprio Bootle', 'DB', 'Los Angeles Chargers', 17),
(97, 'Joey Bosa', 'LB', 'Los Angeles Chargers', 17),
(75, 'Bradley Bozeman', 'C', 'Los Angeles Chargers', 17),
(9, 'D.J. Chark', 'WR', 'Los Angeles Chargers', 17),
(25, 'Junior Colson', 'LB', 'Los Angeles Chargers', 17),
(12, 'Derius Davis', 'WR', 'Los Angeles Chargers', 17),
(11, 'Cameron Dicker', 'K', 'Los Angeles Chargers', 17),
(81, 'Will Dissly', 'TE', 'Los Angeles Chargers', 17),
(27, 'J.K. Dobbins', 'RB', 'Los Angeles Chargers', 17),
(48, 'Alvin Dupree', 'LB', 'Los Angeles Chargers', 17),
(43, 'Troy Dye', 'LB', 'Los Angeles Chargers', 17),
(92, 'Justin Eboigbe', 'DT', 'Los Angeles Chargers', 17),
(87, 'Simi Fehoko', 'WR', 'Los Angeles Chargers', 17),
(24, 'A.J. Finley', 'DB', 'Los Angeles Chargers', 17),
(95, 'Poona Ford', 'DE', 'Los Angeles Chargers', 17),
(56, 'Morgan Fox', 'DE', 'Los Angeles Chargers', 17),
(7, 'Kristian Fulton', 'DB', 'Los Angeles Chargers', 17),
(32, 'Alohi Gilman', 'DB', 'Los Angeles Chargers', 17),
(47, 'Josh Harris', 'LS', 'Los Angeles Chargers', 17),
(20, 'Cam Hart', 'DB', 'Los Angeles Chargers', 17),
(28, 'Hassan Haskins', 'RB', 'Los Angeles Chargers', 17),
(8, 'Taylor Heinicke', 'QB', 'Los Angeles Chargers', 17),
(0, 'Daiyan Henley', 'LB', 'Los Angeles Chargers', 17),
(10, 'Justin Herbert', 'QB', 'Los Angeles Chargers', 17),
(88, 'Hayden Hurst', 'TE', 'Los Angeles Chargers', 17),
(64, 'Brenden Jaimes', 'OG', 'Los Angeles Chargers', 17),
(3, 'Derwin James', 'DB', 'Los Angeles Chargers', 17),
(77, 'Zion Johnson', 'OG', 'Los Angeles Chargers', 17),
(1, 'Quentin Johnston', 'WR', 'Los Angeles Chargers', 17),
(52, 'Khalil Mack', 'LB', 'Los Angeles Chargers', 17),
(44, 'Scott Matlock', 'DT', 'Los Angeles Chargers', 17),
(15, 'Ladd McConkey', 'WR', 'Los Angeles Chargers', 17),
(71, 'Jordan McFadden', 'OG', 'Los Angeles Chargers', 17),
(22, 'Elijah Molden', 'DB', 'Los Angeles Chargers', 17),
(62, 'Sam Mustipher', 'C', 'Los Angeles Chargers', 17),
(31, 'Nick Niemann', 'LB', 'Los Angeles Chargers', 17),
(93, 'Otito Ogbonnia', 'DT', 'Los Angeles Chargers', 17),
(5, 'Josh Palmer', 'WR', 'Los Angeles Chargers', 17),
(6, 'Denzel Perryman', 'LB', 'Los Angeles Chargers', 17),
(79, 'Trey Pipkins', 'OT', 'Los Angeles Chargers', 17),
(89, 'Jalen Reagor', 'WR', 'Los Angeles Chargers', 17),
(68, 'Jamaree Salyer', 'OG', 'Los Angeles Chargers', 17),
(73, 'Foster Sarell', 'OT', 'Los Angeles Chargers', 17),
(16, 'JK Scott', 'P', 'Los Angeles Chargers', 17),
(70, 'Rashawn Slater', 'OT', 'Los Angeles Chargers', 17),
(84, 'Stone Smartt', 'TE', 'Los Angeles Chargers', 17),
(2, 'Easton Stick', 'QB', 'Los Angeles Chargers', 17),
(29, 'Tarheeb Still', 'DB', 'Los Angeles Chargers', 17),
(90, 'Teair Tart', 'DT', 'Los Angeles Chargers', 17),
(36, 'JaSir Taylor', 'DB', 'Los Angeles Chargers', 17),
(83, 'Eric Tomlinson', 'TE', 'Los Angeles Chargers', 17),
(45, 'Tuli Tuipulotu', 'LB', 'Los Angeles Chargers', 17),
(30, 'Kimani Vidal', 'RB', 'Los Angeles Chargers', 17),
(87, 'Davis Allen', 'TE', 'Los Angeles Rams', 18),
(5, 'Chatarius Atwell', 'WR', 'Los Angeles Rams', 18),
(13, 'Stetson Bennett', 'QB', 'Los Angeles Rams', 18),
(95, 'Bobby Brown', 'DT', 'Los Angeles Rams', 18),
(60, 'Logan Bruss', 'OG', 'Los Angeles Rams', 18),
(22, 'Blake Corum', 'RB', 'Los Angeles Rams', 18),
(3, 'Kamren Curl', 'DB', 'Los Angeles Rams', 18),
(90, 'Tyler Davis', 'DE', 'Los Angeles Rams', 18),
(67, 'Justin Dedich', 'OG', 'Los Angeles Rams', 18),
(69, 'Kevin Dotson', 'OG', 'Los Angeles Rams', 18),
(14, 'Decobie Durant', 'DB', 'Los Angeles Rams', 18),
(42, 'Ethan Evans', 'P', 'Los Angeles Rams', 18),
(55, 'Braden Fiske', 'DE', 'Los Angeles Rams', 18),
(92, 'Neville Gallimore', 'DT', 'Los Angeles Rams', 18),
(11, 'Jimmy Garoppolo', 'QB', 'Los Angeles Rams', 18),
(31, 'Nick Hampton', 'LB', 'Los Angeles Rams', 18),
(79, 'Rob Havenstein', 'OT', 'Los Angeles Rams', 18),
(97, 'Michael Hoecht', 'LB', 'Los Angeles Rams', 18),
(35, 'Jake Hummel', 'LB', 'Los Angeles Rams', 18),
(77, 'Alaric Jackson', 'OT', 'Los Angeles Rams', 18),
(44, 'Brennan Jackson', 'LB', 'Los Angeles Rams', 18),
(94, 'Desjuan Johnson', 'DE', 'Los Angeles Rams', 18),
(18, 'Tyler Johnson', 'WR', 'Los Angeles Rams', 18),
(16, 'Joshua Karty', 'K', 'Los Angeles Rams', 18),
(26, 'Kamren Kinchens', 'DB', 'Los Angeles Rams', 18),
(10, 'Cooper Kupp', 'WR', 'Los Angeles Rams', 18),
(37, 'Quentin Lake', 'DB', 'Los Angeles Rams', 18),
(50, 'Beaux Limmer', 'C', 'Los Angeles Rams', 18),
(84, 'Hunter Long', 'TE', 'Los Angeles Rams', 18),
(71, 'Warren McClendon', 'OT', 'Los Angeles Rams', 18),
(39, 'Jaylen McCollough', 'DB', 'Los Angeles Rams', 18),
(63, 'Dylan McMahon', 'C', 'Los Angeles Rams', 18),
(17, 'Puka Nacua', 'WR', 'Los Angeles Rams', 18),
(58, 'Eli Neal', 'LB', 'Los Angeles Rams', 18),
(86, 'Colby Parkinson', 'TE', 'Los Angeles Rams', 18),
(20, 'Ronnie Rivers', 'RB', 'Los Angeles Rams', 18),
(15, 'Demarcus Robinson', 'WR', 'Los Angeles Rams', 18),
(56, 'Christian Rozeboom', 'LB', 'Los Angeles Rams', 18),
(32, 'Cody Schrader', 'RB', 'Los Angeles Rams', 18),
(19, 'Xavier Smith', 'WR', 'Los Angeles Rams', 18),
(48, 'Omar Speights', 'LB', 'Los Angeles Rams', 18),
(9, 'Matthew Stafford', 'QB', 'Los Angeles Rams', 18),
(91, 'Kobie Turner', 'DE', 'Los Angeles Rams', 18),
(8, 'Jared Verse', 'LB', 'Los Angeles Rams', 18),
(30, 'Josh Wallace', 'DB', 'Los Angeles Rams', 18),
(47, 'Alex Ward', 'LS', 'Los Angeles Rams', 18),
(27, 'TreDavious White', 'DB', 'Los Angeles Rams', 18),
(88, 'Jordan Whittington', 'WR', 'Los Angeles Rams', 18),
(24, 'Darious Williams', 'DB', 'Los Angeles Rams', 18),
(93, 'Jonah Williams', 'DE', 'Los Angeles Rams', 18),
(23, 'Kyren Williams', 'RB', 'Los Angeles Rams', 18),
(4, 'Ahkello Witherspoon', 'DB', 'Los Angeles Rams', 18),
(21, 'Charles Woods', 'DB', 'Los Angeles Rams', 18),
(0, 'Byron Young', 'LB', 'Los Angeles Rams', 18),
(46, 'Ty Zentner', 'P', 'Los Angeles Rams', 18),
(8, 'Ameer Abdullah', 'RB', 'Las Vegas Raiders', 19),
(81, 'Alex Bachman', 'WR', 'Las Vegas Raiders', 19),
(0, 'Jakorian Bennett', 'DB', 'Las Vegas Raiders', 19),
(50, 'Jacob Bobenmoyer', 'LS', 'Las Vegas Raiders', 19),
(89, 'Brock Bowers', 'TE', 'Las Vegas Raiders', 19),
(84, 'Harrison Bryant', 'TE', 'Las Vegas Raiders', 19),
(56, 'Amari Burney', 'LB', 'Las Vegas Raiders', 19),
(69, 'Adam Butler', 'DT', 'Las Vegas Raiders', 19),
(91, 'Matthew Butler', 'DT', 'Las Vegas Raiders', 19),
(2, 'Daniel Carlson', 'K', 'Las Vegas Raiders', 19),
(93, 'Zachary Carter', 'DT', 'Las Vegas Raiders', 19),
(44, 'KLavon Chaisson', 'DE', 'Las Vegas Raiders', 19),
(6, 'A.J. Cole', 'P', 'Las Vegas Raiders', 19),
(98, 'Maxx Crosby', 'DE', 'Las Vegas Raiders', 19),
(5, 'Divine Deablo', 'LB', 'Las Vegas Raiders', 19),
(45, 'Tommy Eichenberg', 'LB', 'Las Vegas Raiders', 19),
(53, 'Amari Gainer', 'LB', 'Las Vegas Raiders', 19),
(71, 'Delmar Glaze', 'OT', 'Las Vegas Raiders', 19),
(34, 'Thomas Harper', 'DB', 'Las Vegas Raiders', 19),
(39, 'Nate Hobbs', 'DB', 'Las Vegas Raiders', 19),
(30, 'Darnay Holmes', 'DB', 'Las Vegas Raiders', 19),
(68, 'Andre James', 'C', 'Las Vegas Raiders', 19),
(95, 'John Jenkins', 'DT', 'Las Vegas Raiders', 19),
(18, 'Jack Jones', 'DB', 'Las Vegas Raiders', 19),
(82, 'Ramel Keyton', 'WR', 'Las Vegas Raiders', 19),
(23, 'Dylan Laube', 'RB', 'Las Vegas Raiders', 19),
(96, 'Jonah Laulu', 'DT', 'Las Vegas Raiders', 19),
(22, 'Alexander Mattison', 'RB', 'Las Vegas Raiders', 19),
(43, 'Kanai Mauga', 'LB', 'Las Vegas Raiders', 19),
(61, 'Jordan Meredith', 'OG', 'Las Vegas Raiders', 19),
(16, 'Jakobi Meyers', 'WR', 'Las Vegas Raiders', 19),
(74, 'Kolton Miller', 'OT', 'Las Vegas Raiders', 19),
(15, 'Gardner Minshew', 'QB', 'Las Vegas Raiders', 19),
(7, 'Trevon Moehrig', 'DB', 'Las Vegas Raiders', 19),
(77, 'Thayer Munford', 'OT', 'Las Vegas Raiders', 19),
(66, 'Dylan Parham', 'OG', 'Las Vegas Raiders', 19),
(75, 'Andrus Peat', 'OT', 'Las Vegas Raiders', 19),
(20, 'Isaiah Pola-Mao', 'DB', 'Las Vegas Raiders', 19),
(58, 'Jackson Powers-Johnson', 'OG', 'Las Vegas Raiders', 19),
(25, 'Decamerion Richardson', 'DB', 'Las Vegas Raiders', 19),
(10, 'Desmond Ridder', 'QB', 'Las Vegas Raiders', 19),
(97, 'Janarius Robinson', 'DE', 'Las Vegas Raiders', 19),
(88, 'Justin Shorter', 'TE', 'Las Vegas Raiders', 19),
(29, 'Christopher Smith', 'DB', 'Las Vegas Raiders', 19),
(49, 'Charles Snowden', 'DE', 'Las Vegas Raiders', 19),
(41, 'Robert Spillane', 'LB', 'Las Vegas Raiders', 19),
(37, 'Trey Taylor', 'DB', 'Las Vegas Raiders', 19),
(11, 'Tre Tucker', 'WR', 'Las Vegas Raiders', 19),
(19, 'D.J. Turner', 'WR', 'Las Vegas Raiders', 19),
(27, 'Sam Webb', 'DB', 'Las Vegas Raiders', 19),
(3, 'Zamir White', 'RB', 'Las Vegas Raiders', 19),
(65, 'Cody Whitehair', 'OG', 'Las Vegas Raiders', 19),
(9, 'Tyree Wilson', 'DE', 'Las Vegas Raiders', 19),
(28, 'DeVon Achane', 'RB', 'Miami Dolphins', 20),
(72, 'Terron Armstead', 'OT', 'Miami Dolphins', 20),
(16, 'Jake Bailey', 'P', 'Miami Dolphins', 20),
(3, 'Odell Beckham Jr.', 'WR', 'Miami Dolphins', 20),
(56, 'Quinton Bell', 'LB', 'Miami Dolphins', 20),
(27, 'Ethan Bonner', 'DB', 'Miami Dolphins', 20),
(51, 'Tyus Bowser', 'LB', 'Miami Dolphins', 20),
(55, 'Aaron Brewer', 'OG', 'Miami Dolphins', 20),
(20, 'Jordyn Brooks', 'LB', 'Miami Dolphins', 20),
(93, 'Calais Campbell', 'DT', 'Miami Dolphins', 20),
(22, 'Elijah Campbell', 'DB', 'Miami Dolphins', 20),
(80, 'Tanner Conner', 'TE', 'Miami Dolphins', 20),
(66, 'Lester Cotton', 'OG', 'Miami Dolphins', 20),
(36, 'Storm Duck', 'DB', 'Miami Dolphins', 20),
(74, 'Liam Eichenberg', 'OT', 'Miami Dolphins', 20),
(82, 'DWayne Eskridge', 'WR', 'Miami Dolphins', 20),
(97, 'Neil Farrell', 'DT', 'Miami Dolphins', 20),
(29, 'Kendall Fuller', 'DB', 'Miami Dolphins', 20),
(90, 'DaShawn Hand', 'DT', 'Miami Dolphins', 20),
(89, 'Julian Hill', 'TE', 'Miami Dolphins', 20),
(10, 'Tyreek Hill', 'WR', 'Miami Dolphins', 20),
(8, 'Jevon Holland', 'DB', 'Miami Dolphins', 20),
(30, 'Alec Ingold', 'RB', 'Miami Dolphins', 20),
(73, 'Austin Jackson', 'OG', 'Miami Dolphins', 20),
(95, 'Benito Jones', 'DT', 'Miami Dolphins', 20),
(65, 'Robert Jones', 'OG', 'Miami Dolphins', 20),
(50, 'Mohamed Kamara', 'LB', 'Miami Dolphins', 20),
(4, 'Kader Kohou', 'DB', 'Miami Dolphins', 20),
(70, 'Kendall Lamm', 'OT', 'Miami Dolphins', 20),
(11, 'David Long', 'LB', 'Miami Dolphins', 20),
(26, 'Marcus Maye', 'DB', 'Miami Dolphins', 20),
(60, 'Andrew Meyer', 'OT', 'Miami Dolphins', 20),
(31, 'Raheem Mostert', 'RB', 'Miami Dolphins', 20),
(33, 'Siran Neal', 'DB', 'Miami Dolphins', 20),
(91, 'Emmanuel Ogbah', 'LB', 'Miami Dolphins', 20),
(49, 'Matt Overton', 'LS', 'Miami Dolphins', 20),
(52, 'Patrick Paul', 'OT', 'Miami Dolphins', 20),
(96, 'Brandon Pili', 'DT', 'Miami Dolphins', 20),
(21, 'Jordan Poyer', 'DB', 'Miami Dolphins', 20),
(5, 'Jalen Ramsey', 'DB', 'Miami Dolphins', 20),
(45, 'Duke Riley', 'LB', 'Miami Dolphins', 20),
(44, 'Demeioun Robinson', 'LB', 'Miami Dolphins', 20),
(7, 'Jason Sanders', 'K', 'Miami Dolphins', 20),
(92, 'Zach Sieler', 'DT', 'Miami Dolphins', 20),
(24, 'Cam Smith', 'DB', 'Miami Dolphins', 20),
(9, 'Jonnu Smith', 'TE', 'Miami Dolphins', 20),
(81, 'Durham Smythe', 'TE', 'Miami Dolphins', 20),
(1, 'Tua Tagovailoa', 'QB', 'Miami Dolphins', 20),
(19, 'Skylar Thompson', 'QB', 'Miami Dolphins', 20),
(41, 'Channing Tindall', 'LB', 'Miami Dolphins', 20),
(17, 'Jaylen Waddle', 'WR', 'Miami Dolphins', 20),
(6, 'Anthony Walker', 'LB', 'Miami Dolphins', 20),
(83, 'Malik Washington', 'WR', 'Miami Dolphins', 20),
(23, 'Jeffery Wilson', 'RB', 'Miami Dolphins', 20),
(25, 'Jaylen Wright', 'RB', 'Miami Dolphins', 20),
(3, 'Jordan Addison', 'WR', 'Minnesota Vikings', 21),
(27, 'Cam Akers', 'RB', 'Minnesota Vikings', 21),
(6, 'Brian Asamoah', 'LB', 'Minnesota Vikings', 21),
(56, 'Garrett Bradbury', 'C', 'Minnesota Vikings', 21),
(64, 'Blake Brandel', 'OG', 'Minnesota Vikings', 21),
(90, 'Jonathan Bullard', 'DE', 'Minnesota Vikings', 21),
(24, 'Camryn Bynum', 'DB', 'Minnesota Vikings', 21),
(51, 'Blake Cashman', 'LB', 'Minnesota Vikings', 21),
(32, 'Ty Chandler', 'RB', 'Minnesota Vikings', 21),
(14, 'Sam Darnold', 'QB', 'Minnesota Vikings', 21),
(42, 'Andrew DePaola', 'LS', 'Minnesota Vikings', 21),
(21, 'Akayleb Evans', 'DB', 'Minnesota Vikings', 21),
(69, 'Dan Feeney', 'C', 'Minnesota Vikings', 21),
(2, 'Stephon Gilmore', 'DB', 'Minnesota Vikings', 21),
(58, 'Jonathan Greenard', 'LB', 'Minnesota Vikings', 21),
(1, 'Shaquill Griffin', 'DB', 'Minnesota Vikings', 21),
(54, 'Kamu Grugier-Hill', 'LB', 'Minnesota Vikings', 21),
(30, 'C.J. Ham', 'RB', 'Minnesota Vikings', 21),
(87, 'T.J. Hockenson', 'TE', 'Minnesota Vikings', 21),
(67, 'Edward Ingram', 'OG', 'Minnesota Vikings', 21),
(26, 'Theo Jackson', 'DB', 'Minnesota Vikings', 21),
(18, 'Justin Jefferson', 'WR', 'Minnesota Vikings', 21),
(33, 'Aaron Jones', 'RB', 'Minnesota Vikings', 21),
(91, 'Patrick Jones', 'LB', 'Minnesota Vikings', 21),
(65, 'Michael Jurgens', 'OG', 'Minnesota Vikings', 21),
(29, 'Dwight McGlothern', 'DB', 'Minnesota Vikings', 21),
(44, 'Josh Metellus', 'DB', 'Minnesota Vikings', 21),
(23, 'Fabian Moreau', 'DB', 'Minnesota Vikings', 21),
(12, 'Nick Mullens', 'QB', 'Minnesota Vikings', 21),
(86, 'John Mundt', 'TE', 'Minnesota Vikings', 21),
(7, 'Byron Murphy', 'DB', 'Minnesota Vikings', 21),
(83, 'Jalen Nailor', 'WR', 'Minnesota Vikings', 21),
(75, 'Brian ONeill', 'OT', 'Minnesota Vikings', 21),
(84, 'Josh Oliver', 'TE', 'Minnesota Vikings', 21),
(0, 'Ivan Pace', 'LB', 'Minnesota Vikings', 21),
(97, 'Harrison Phillips', 'DT', 'Minnesota Vikings', 21),
(4, 'Brandon Powell', 'WR', 'Minnesota Vikings', 21),
(76, 'David Quessenberry', 'OT', 'Minnesota Vikings', 21),
(61, 'Jalen Redmond', 'DE', 'Minnesota Vikings', 21),
(16, 'Will Reichard', 'K', 'Minnesota Vikings', 21),
(98, 'Bo Richter', 'LB', 'Minnesota Vikings', 21),
(66, 'Dalton Risner', 'OG', 'Minnesota Vikings', 21),
(74, 'Cam Robinson', 'OT', 'Minnesota Vikings', 21),
(50, 'Levi Drake Rodriguez', 'DT', 'Minnesota Vikings', 21),
(78, 'Walter Rouse', 'OT', 'Minnesota Vikings', 21),
(19, 'Brett Rypien', 'QB', 'Minnesota Vikings', 21),
(11, 'Trent Sherfield', 'WR', 'Minnesota Vikings', 21),
(22, 'Harrison Smith', 'DB', 'Minnesota Vikings', 21),
(99, 'Jerry Tillery', 'DT', 'Minnesota Vikings', 21),
(15, 'Dallas Turner', 'LB', 'Minnesota Vikings', 21),
(43, 'Andrew Van Ginkel', 'LB', 'Minnesota Vikings', 21),
(20, 'Jay Ward', 'DB', 'Minnesota Vikings', 21),
(52, 'Jihad Ward', 'LB', 'Minnesota Vikings', 21),
(17, 'Ryan Wright', 'P', 'Minnesota Vikings', 21),
(6, 'Javon Baker', 'WR', 'New England Patriots', 22),
(17, 'Bryce Baringer', 'P', 'New England Patriots', 22),
(88, 'Jaheim Bell', 'TE', 'New England Patriots', 22),
(29, 'Isaiah Bolden', 'DB', 'New England Patriots', 22),
(84, 'Kendrick Bourne', 'WR', 'New England Patriots', 22),
(9, 'Kayshon Boutte', 'WR', 'New England Patriots', 22),
(7, 'Jacoby Brissett', 'QB', 'New England Patriots', 22),
(77, 'Ben Brown', 'C', 'New England Patriots', 22),
(49, 'Joe Cardona', 'LS', 'New England Patriots', 22),
(27, 'Marcellas Dial', 'DB', 'New England Patriots', 22),
(3, 'Demario Douglas', 'WR', 'New England Patriots', 22),
(23, 'Kyle Dugger', 'DB', 'New England Patriots', 22),
(95, 'Daniel Ekuale', 'DT', 'New England Patriots', 22),
(53, 'Christian Elliss', 'LB', 'New England Patriots', 22),
(4, 'Antonio Gibson', 'RB', 'New England Patriots', 22),
(92, 'Davon Godchaux', 'DT', 'New England Patriots', 22),
(0, 'Christian Gonzalez', 'DB', 'New England Patriots', 22),
(39, 'JaMycal Hasty', 'RB', 'New England Patriots', 22),
(21, 'Jaylinn Hawkins', 'DB', 'New England Patriots', 22),
(85, 'Hunter Henry', 'TE', 'New England Patriots', 22),
(81, 'Austin Hooper', 'TE', 'New England Patriots', 22),
(52, 'Curtis Jacobs', 'LB', 'New England Patriots', 22),
(75, 'Demontrey Jacobs', 'OT', 'New England Patriots', 22),
(33, 'Anfernee Jennings', 'LB', 'New England Patriots', 22),
(96, 'Eric Johnson', 'DT', 'New England Patriots', 22),
(31, 'Jonathan Jones', 'DB', 'New England Patriots', 22),
(25, 'Marcus Jones', 'DB', 'New England Patriots', 22),
(74, 'Michael Jordan', 'OG', 'New England Patriots', 22),
(59, 'Vederian Lowe', 'OT', 'New England Patriots', 22),
(15, 'Marte Mapu', 'DB', 'New England Patriots', 22),
(32, 'Ochaun Mathis', 'LB', 'New England Patriots', 22),
(10, 'Drake Maye', 'QB', 'New England Patriots', 22),
(50, 'Raekwon McMillan', 'LB', 'New England Patriots', 22),
(19, 'Joe Milton', 'QB', 'New England Patriots', 22),
(71, 'Michael Onwenu', 'OG', 'New England Patriots', 22),
(2, 'K.J. Osborn', 'WR', 'New England Patriots', 22),
(24, 'Dell Pettus', 'DB', 'New England Patriots', 22),
(98, 'Jeremiah Pharms Jr.', 'DT', 'New England Patriots', 22),
(1, 'JaLynn Polk', 'WR', 'New England Patriots', 22),
(64, 'Layden Robinson', 'OG', 'New England Patriots', 22),
(94, 'Jaquelin Roy', 'DT', 'New England Patriots', 22),
(41, 'Brenden Schooler', 'DB', 'New England Patriots', 22),
(13, 'Joey Slye', 'K', 'New England Patriots', 22),
(68, 'Lecitus Smith', 'C', 'New England Patriots', 22),
(62, 'Sidy Sow', 'OG', 'New England Patriots', 22),
(38, 'Rhamondre Stevenson', 'RB', 'New England Patriots', 22),
(16, 'Sione Takitaki', 'LB', 'New England Patriots', 22),
(48, 'Jahlani Tavai', 'LB', 'New England Patriots', 22),
(72, 'Zachary Thomas', 'OT', 'New England Patriots', 22),
(11, 'Tyquan Thornton', 'WR', 'New England Patriots', 22),
(99, 'Keion White', 'DE', 'New England Patriots', 22),
(22, 'Marco Wilson', 'DB', 'New England Patriots', 22),
(91, 'Deatrich Wise', 'DE', 'New England Patriots', 22),
(0, 'Ugo Amadi', 'DB', 'New Orleans Saints', 23),
(97, 'Khristian Boyd', 'DT', 'New Orleans Saints', 23),
(38, 'Nook Bradford', 'DB', 'New Orleans Saints', 23),
(90, 'Bryan Bresee', 'DT', 'New Orleans Saints', 23),
(4, 'Derek Carr', 'QB', 'New Orleans Saints', 23),
(56, 'Demario Davis', 'LB', 'New Orleans Saints', 23),
(53, 'Jaylan Ford', 'LB', 'New Orleans Saints', 23),
(55, 'Isaiah Foskey', 'DE', 'New Orleans Saints', 23),
(75, 'Taliese Fuaga', 'OT', 'New Orleans Saints', 23),
(6, 'Willie Gay', 'LB', 'New Orleans Saints', 23),
(96, 'Carl Granderson', 'DE', 'New Orleans Saints', 23),
(48, 'J.T. Gray', 'DB', 'New Orleans Saints', 23),
(19, 'Blake Grupe', 'K', 'New Orleans Saints', 23),
(3, 'Jake Haener', 'QB', 'New Orleans Saints', 23),
(43, 'Matt Hayball', 'P', 'New Orleans Saints', 23),
(28, 'Tre Herndon', 'DB', 'New Orleans Saints', 23),
(7, 'Taysom Hill', 'TE', 'New Orleans Saints', 23),
(85, 'Dallin Holker', 'TE', 'New Orleans Saints', 23),
(31, 'Jordan Howden', 'DB', 'New Orleans Saints', 23),
(52, 'DMarco Jackson', 'LB', 'New Orleans Saints', 23),
(80, 'Jermaine Jackson', 'WR', 'New Orleans Saints', 23),
(27, 'Shemar Jean-Charles', 'DB', 'New Orleans Saints', 23),
(83, 'Juwan Johnson', 'TE', 'New Orleans Saints', 23),
(94, 'Cameron Jordan', 'DE', 'New Orleans Saints', 23),
(41, 'Alvin Kamara', 'RB', 'New Orleans Saints', 23),
(23, 'Marshon Lattimore', 'DB', 'New Orleans Saints', 23),
(32, 'Tyrann Mathieu', 'DB', 'New Orleans Saints', 23),
(61, 'Connor McGovern', 'C', 'New Orleans Saints', 23),
(14, 'GaQuincy McKinstry', 'DB', 'New Orleans Saints', 23),
(33, 'Jordan Mims', 'RB', 'New Orleans Saints', 23),
(87, 'Foster Moreau', 'TE', 'New Orleans Saints', 23),
(12, 'Chris Olave', 'WR', 'New Orleans Saints', 23),
(58, 'Anfernee Orji', 'LB', 'New Orleans Saints', 23),
(62, 'Lucas Patrick', 'OG', 'New Orleans Saints', 23),
(36, 'Rico Payton', 'DB', 'New Orleans Saints', 23),
(70, 'Trevor Penning', 'OT', 'New Orleans Saints', 23),
(46, 'Adam Prentice', 'RB', 'New Orleans Saints', 23),
(18, 'Spencer Rattler', 'QB', 'New Orleans Saints', 23),
(95, 'John Ridgeway', 'DT', 'New Orleans Saints', 23),
(51, 'Cesar Ruiz', 'OG', 'New Orleans Saints', 23),
(64, 'Nick Saldiveri', 'OG', 'New Orleans Saints', 23),
(50, 'Khalen Saunders', 'DT', 'New Orleans Saints', 23),
(93, 'Nathan Shepherd', 'DT', 'New Orleans Saints', 23),
(1, 'Alontae Taylor', 'DB', 'New Orleans Saints', 23),
(30, 'Roderic Teamer', 'DB', 'New Orleans Saints', 23),
(84, 'Mason Tipton', 'WR', 'New Orleans Saints', 23),
(98, 'Payton Turner', 'DE', 'New Orleans Saints', 23),
(74, 'Olisaemeka Udoh', 'OG', 'New Orleans Saints', 23),
(10, 'Marquez Valdes-Scantling', 'WR', 'New Orleans Saints', 23),
(20, 'Pete Werner', 'LB', 'New Orleans Saints', 23),
(21, 'Jamaal Williams', 'RB', 'New Orleans Saints', 23),
(11, 'Cedrick Wilson', 'WR', 'New Orleans Saints', 23),
(49, 'Zach Wood', 'LS', 'New Orleans Saints', 23),
(99, 'Chase Young', 'DE', 'New Orleans Saints', 23),
(67, 'Landon Young', 'OT', 'New Orleans Saints', 23),
(49, 'Matthew Adams', 'LB', 'New York Giants', 24),
(3, 'Deonte Banks', 'DB', 'New York Giants', 24),
(82, 'Daniel Bellinger', 'TE', 'New York Giants', 24),
(24, 'Dane Belton', 'DB', 'New York Giants', 24),
(0, 'Brian Burns', 'LB', 'New York Giants', 24),
(94, 'Elijah Chatman', 'DT', 'New York Giants', 24),
(98, 'D.J. Davidson', 'DT', 'New York Giants', 24),
(15, 'Tommy DeVito', 'QB', 'New York Giants', 24),
(72, 'Jermaine Eluemunor', 'OT', 'New York Giants', 24),
(75, 'Joshua Ezeudu', 'OT', 'New York Giants', 24),
(28, 'Cordale Flott', 'DB', 'New York Giants', 24),
(88, 'Bryce Ford-Wheaton', 'WR', 'New York Giants', 24),
(45, 'Tomon Fox', 'LB', 'New York Giants', 24),
(6, 'Jamie Gillan', 'P', 'New York Giants', 24),
(20, 'Eric Gray', 'RB', 'New York Giants', 24),
(38, 'Matt Haack', 'P', 'New York Giants', 24),
(37, 'Tre Hawkins', 'DB', 'New York Giants', 24),
(70, 'Chris Hubbard', 'OT', 'New York Giants', 24),
(13, 'Jalin Hyatt', 'WR', 'New York Giants', 24),
(21, 'Adoree Jackson', 'DB', 'New York Giants', 24),
(23, 'Anthony Johnson', 'DB', 'New York Giants', 24),
(57, 'Patrick Johnson', 'LB', 'New York Giants', 24),
(47, 'Theo Johnson', 'TE', 'New York Giants', 24),
(8, 'Daniel Jones', 'QB', 'New York Giants', 24),
(59, 'Casey Kreiter', 'LS', 'New York Giants', 24),
(63, 'Jake Kubas', 'OG', 'New York Giants', 24),
(97, 'Dexter Lawrence', 'DE', 'New York Giants', 24),
(2, 'Drew Lock', 'QB', 'New York Giants', 24),
(85, 'Chris Manhertz', 'TE', 'New York Giants', 24),
(99, 'Jude McAtamney', 'K', 'New York Giants', 24),
(44, 'Nick McCloud', 'DB', 'New York Giants', 24),
(41, 'Micah McFadden', 'LB', 'New York Giants', 24),
(53, 'Darius Muasau', 'LB', 'New York Giants', 24),
(1, 'Malik Nabers', 'WR', 'New York Giants', 24),
(73, 'Evan Neal', 'OT', 'New York Giants', 24),
(31, 'Tyler Nubin', 'DB', 'New York Giants', 24),
(93, 'Rakeem Nunez-Roches', 'DT', 'New York Giants', 24),
(51, 'Azeez Ojulari', 'LB', 'New York Giants', 24),
(58, 'Bobby Okereke', 'LB', 'New York Giants', 24),
(22, 'Andru Phillips', 'DB', 'New York Giants', 24),
(27, 'Jason Pinnock', 'DB', 'New York Giants', 24),
(95, 'Jordon Riley', 'DT', 'New York Giants', 24),
(17, 'WanDale Robinson', 'WR', 'New York Giants', 24),
(76, 'Jon Runyan', 'OG', 'New York Giants', 24),
(61, 'John Michael Schmitz', 'C', 'New York Giants', 24),
(19, 'Isaiah Simmons', 'LB', 'New York Giants', 24),
(26, 'Devin Singletary', 'RB', 'New York Giants', 24),
(86, 'Darius Slayton', 'WR', 'New York Giants', 24),
(87, 'Ihmir Smith-Marsette', 'WR', 'New York Giants', 24),
(64, 'Aaron Stinnie', 'OG', 'New York Giants', 24),
(47, 'Ty Summers', 'LB', 'New York Giants', 24),
(29, 'Tyrone Tracy', 'RB', 'New York Giants', 24),
(74, 'Greg Van Roten', 'OG', 'New York Giants', 24),
(96, 'Armon Watts', 'DT', 'New York Giants', 24),
(25, 'Israel Abanikanda', 'RB', 'New York Jets', 25),
(17, 'Davante Adams', 'WR', 'New York Jets', 25),
(22, 'Tony Adams', 'DB', 'New York Jets', 25),
(0, 'Braelon Allen', 'RB', 'New York Jets', 25),
(29, 'Jarrick Bernard', 'DB', 'New York Jets', 25),
(30, 'Michael Carter', 'DB', 'New York Jets', 25),
(19, 'Irvin Charles', 'WR', 'New York Jets', 25),
(72, 'Micheal Clemons', 'DE', 'New York Jets', 25),
(83, 'Tyler Conklin', 'TE', 'New York Jets', 25),
(14, 'Malachi Corley', 'WR', 'New York Jets', 25),
(21, 'Ashtyn Davis', 'DB', 'New York Jets', 25),
(32, 'Isaiah Davis', 'RB', 'New York Jets', 25),
(26, 'Brandin Echols', 'DB', 'New York Jets', 25),
(52, 'Samuel Eguavoen', 'LB', 'New York Jets', 25),
(74, 'Olu Fashanu', 'OT', 'New York Jets', 25),
(1, 'Ahmad Gardner', 'DB', 'New York Jets', 25),
(82, 'Xavier Gipson', 'WR', 'New York Jets', 25),
(20, 'Breece Hall', 'RB', 'New York Jets', 25),
(62, 'Jake Hanson', 'OG', 'New York Jets', 25),
(42, 'Thomas Hennessy', 'LS', 'New York Jets', 25),
(54, 'Javon Kinlaw', 'DT', 'New York Jets', 25),
(70, 'Alec Lindstrom', 'C', 'New York Jets', 25),
(41, 'Marcelino McCrary-Ball', 'LB', 'New York Jets', 25),
(99, 'Will McDonald', 'DE', 'New York Jets', 25),
(91, 'Braiden McGregor', 'DE', 'New York Jets', 25),
(35, 'Jalen Mills', 'DB', 'New York Jets', 25),
(61, 'Max Mitchell', 'OT', 'New York Jets', 25),
(6, 'Thomas Morstead', 'P', 'New York Jets', 25),
(78, 'Morgan Moses', 'OT', 'New York Jets', 25),
(57, 'C.J. Mosley', 'LB', 'New York Jets', 25),
(23, 'Isaiah Oliver', 'DB', 'New York Jets', 25),
(46, 'Riley Patterson', 'K', 'New York Jets', 25),
(7, 'Haason Reddick', 'LB', 'New York Jets', 25),
(4, 'D.J. Reed', 'DB', 'New York Jets', 25),
(8, 'Aaron Rodgers', 'QB', 'New York Jets', 25),
(89, 'Jeremy Ruckert', 'TE', 'New York Jets', 25),
(44, 'Jamien Sherwood', 'LB', 'New York Jets', 25),
(76, 'John Simpson', 'OG', 'New York Jets', 25),
(77, 'Tyron Smith', 'OT', 'New York Jets', 25),
(37, 'Qwantez Stiggers', 'DB', 'New York Jets', 25),
(55, 'Chazz Surratt', 'LB', 'New York Jets', 25),
(96, 'Leonard Taylor', 'DT', 'New York Jets', 25),
(2, 'Tyrod Taylor', 'QB', 'New York Jets', 25),
(94, 'Solomon Thomas', 'DE', 'New York Jets', 25),
(66, 'Joe Tippmann', 'C', 'New York Jets', 25),
(75, 'Alijah Vera-Tucker', 'OG', 'New York Jets', 25),
(67, 'Carter Warren', 'OT', 'New York Jets', 25),
(58, 'Eric Watts', 'DE', 'New York Jets', 25),
(18, 'Mike Williams', 'WR', 'New York Jets', 25),
(56, 'Quincy Williams', 'LB', 'New York Jets', 25),
(95, 'Quinnen Williams', 'DT', 'New York Jets', 25),
(5, 'Garrett Wilson', 'WR', 'New York Jets', 25),
(88, 'Kenny Yeboah', 'TE', 'New York Jets', 25),
(26, 'Saquon Barkley', 'RB', 'Philadelphia Eagles', 26),
(53, 'Zack Baun', 'LB', 'Philadelphia Eagles', 26),
(77, 'Mekhi Becton', 'OT', 'Philadelphia Eagles', 26),
(32, 'Reed Blankenship', 'DB', 'Philadelphia Eagles', 26),
(59, 'Thomas Booker', 'DT', 'Philadelphia Eagles', 26),
(11, 'A.J. Brown', 'WR', 'Philadelphia Eagles', 26),
(21, 'Sydney Brown', 'DB', 'Philadelphia Eagles', 26),
(42, 'Oren Burks', 'LB', 'Philadelphia Eagles', 26),
(81, 'Grant Calcaterra', 'TE', 'Philadelphia Eagles', 26),
(98, 'Jalen Carter', 'DT', 'Philadelphia Eagles', 26),
(90, 'Jordan Davis', 'DT', 'Philadelphia Eagles', 26),
(17, 'Nakobe Dean', 'LB', 'Philadelphia Eagles', 26),
(33, 'Cooper DeJean', 'DB', 'Philadelphia Eagles', 26),
(69, 'Landon Dickerson', 'OG', 'Philadelphia Eagles', 26),
(83, 'Jahan Dotson', 'WR', 'Philadelphia Eagles', 26),
(75, 'Jack Driscoll', 'OT', 'Philadelphia Eagles', 26),
(4, 'Jake Elliott', 'K', 'Philadelphia Eagles', 26),
(14, 'Kenny Gainwell', 'RB', 'Philadelphia Eagles', 26),
(8, 'Chauncey Gardner-Johnson', 'DB', 'Philadelphia Eagles', 26),
(61, 'Nick Gates', 'C', 'Philadelphia Eagles', 26),
(88, 'Dallas Goedert', 'TE', 'Philadelphia Eagles', 26),
(55, 'Brandon Graham', 'DE', 'Philadelphia Eagles', 26),
(0, 'Bryce Huff', 'DE', 'Philadelphia Eagles', 26),
(58, 'Jalyx Hunt', 'LB', 'Philadelphia Eagles', 26),
(1, 'Jalen Hurts', 'QB', 'Philadelphia Eagles', 26),
(84, 'E.J. Jenkins', 'TE', 'Philadelphia Eagles', 26),
(74, 'Fred Johnson', 'OT', 'Philadelphia Eagles', 26),
(65, 'Lane Johnson', 'OT', 'Philadelphia Eagles', 26),
(51, 'Cameron Jurgens', 'OG', 'Philadelphia Eagles', 26),
(79, 'Trevor Keegan', 'OG', 'Philadelphia Eagles', 26),
(72, 'Darian Kinnard', 'OT', 'Philadelphia Eagles', 26),
(49, 'Rick Lovato', 'LS', 'Philadelphia Eagles', 26),
(29, 'Avonte Maddox', 'DB', 'Philadelphia Eagles', 26),
(10, 'Braden Mann', 'P', 'Philadelphia Eagles', 26),
(36, 'Tristin McCollum', 'DB', 'Philadelphia Eagles', 26),
(16, 'Tanner McKee', 'QB', 'Philadelphia Eagles', 26),
(27, 'Quinyon Mitchell', 'DB', 'Philadelphia Eagles', 26),
(97, 'Moro Ojomo', 'DT', 'Philadelphia Eagles', 26),
(7, 'Kenny Pickett', 'QB', 'Philadelphia Eagles', 26),
(23, 'Eli Ricks', 'DB', 'Philadelphia Eagles', 26),
(22, 'Kelee Ringo', 'DB', 'Philadelphia Eagles', 26),
(34, 'Isaiah Rodgers', 'DB', 'Philadelphia Eagles', 26),
(28, 'Will Shipley', 'RB', 'Philadelphia Eagles', 26),
(2, 'Darius Slay', 'DB', 'Philadelphia Eagles', 26),
(82, 'Ainias Smith', 'WR', 'Philadelphia Eagles', 26),
(6, 'DeVonta Smith', 'WR', 'Philadelphia Eagles', 26),
(3, 'Nolan Smith', 'LB', 'Philadelphia Eagles', 26),
(56, 'Tyler Steen', 'OT', 'Philadelphia Eagles', 26),
(87, 'Jack Stoll', 'TE', 'Philadelphia Eagles', 26),
(19, 'Josh Sweat', 'LB', 'Philadelphia Eagles', 26),
(54, 'Jeremiah Trotter', 'LB', 'Philadelphia Eagles', 26),
(57, 'Ben VanSumeren', 'LB', 'Philadelphia Eagles', 26),
(93, 'Milton Williams', 'DT', 'Philadelphia Eagles', 26),
(89, 'Johnny Wilson', 'WR', 'Philadelphia Eagles', 26),
(4, 'Kyle Allen', 'QB', 'Pittsburgh Steelers', 27),
(67, 'Calvin Anderson', 'OT', 'Pittsburgh Steelers', 27),
(74, 'Spencer Anderson', 'OT', 'Pittsburgh Steelers', 27),
(19, 'Calvin Austin', 'WR', 'Pittsburgh Steelers', 27),
(95, 'Keeanu Benton', 'DT', 'Pittsburgh Steelers', 27),
(31, 'Beanie Bishop', 'DB', 'Pittsburgh Steelers', 27),
(9, 'Chris Boswell', 'K', 'Pittsburgh Steelers', 27),
(38, 'Terrell Edmunds', 'DB', 'Pittsburgh Steelers', 27),
(25, 'DeShon Elliott', 'DB', 'Pittsburgh Steelers', 27),
(2, 'Justin Fields', 'QB', 'Pittsburgh Steelers', 27),
(39, 'Minkah Fitzpatrick', 'DB', 'Pittsburgh Steelers', 27),
(54, 'Zach Frazier', 'C', 'Pittsburgh Steelers', 27),
(88, 'Pat Freiermuth', 'TE', 'Pittsburgh Steelers', 27),
(22, 'Najee Harris', 'RB', 'Pittsburgh Steelers', 27),
(21, 'C.J. Henderson', 'DB', 'Pittsburgh Steelers', 27),
(51, 'Nick Herbig', 'LB', 'Pittsburgh Steelers', 27),
(97, 'Cameron Heyward', 'DT', 'Pittsburgh Steelers', 27),
(83, 'Connor Heyward', 'RB', 'Pittsburgh Steelers', 27),
(56, 'Alex Highsmith', 'LB', 'Pittsburgh Steelers', 27),
(26, 'Donte Jackson', 'DB', 'Pittsburgh Steelers', 27),
(11, 'Van Jefferson', 'WR', 'Pittsburgh Steelers', 27),
(77, 'Broderick Jones', 'OT', 'Pittsburgh Steelers', 27),
(23, 'Damontae Kazee', 'DB', 'Pittsburgh Steelers', 27),
(28, 'Miles Killebrew', 'DB', 'Pittsburgh Steelers', 27),
(46, 'Christian Kuntz', 'LS', 'Pittsburgh Steelers', 27),
(92, 'Isaiahh Loudermilk', 'DT', 'Pittsburgh Steelers', 27),
(94, 'Dean Lowry', 'DT', 'Pittsburgh Steelers', 27),
(62, 'Ryan McCollum', 'C', 'Pittsburgh Steelers', 27),
(66, 'Mason McCormick', 'OG', 'Pittsburgh Steelers', 27),
(13, 'Scott Miller', 'WR', 'Pittsburgh Steelers', 27),
(49, 'Jeremiah Moon', 'LB', 'Pittsburgh Steelers', 27),
(65, 'Dan Moore', 'OT', 'Pittsburgh Steelers', 27),
(99, 'Larry Ogunjobi', 'DT', 'Pittsburgh Steelers', 27),
(84, 'Cordarrelle Patterson', 'RB', 'Pittsburgh Steelers', 27),
(14, 'George Pickens', 'WR', 'Pittsburgh Steelers', 27),
(42, 'James Pierre', 'DB', 'Pittsburgh Steelers', 27),
(24, 'Joey Porter Jr.', 'DB', 'Pittsburgh Steelers', 27),
(81, 'MyCole Pruitt', 'TE', 'Pittsburgh Steelers', 27),
(6, 'Patrick Queen', 'LB', 'Pittsburgh Steelers', 27),
(50, 'Elandon Roberts', 'LB', 'Pittsburgh Steelers', 27),
(93, 'Mark Robinson', 'LB', 'Pittsburgh Steelers', 27),
(64, 'Max Scharping', 'OG', 'Pittsburgh Steelers', 27),
(73, 'Isaac Seumalo', 'OG', 'Pittsburgh Steelers', 27),
(20, 'Cameron Sutton', 'DB', 'Pittsburgh Steelers', 27),
(8, 'Corliss Waitman', 'P', 'Pittsburgh Steelers', 27),
(35, 'Jonathan Ward', 'RB', 'Pittsburgh Steelers', 27),
(30, 'Jaylen Warren', 'RB', 'Pittsburgh Steelers', 27),
(80, 'Darnell Washington', 'TE', 'Pittsburgh Steelers', 27),
(90, 'T.J. Watt', 'LB', 'Pittsburgh Steelers', 27),
(87, 'Rodney Williams', 'TE', 'Pittsburgh Steelers', 27),
(41, 'Payton Wilson', 'LB', 'Pittsburgh Steelers', 27),
(3, 'Russell Wilson', 'QB', 'Pittsburgh Steelers', 27),
(17, 'Brandon Allen', 'QB', 'San Francisco 49ers', 28),
(69, 'Evan Anderson', 'DT', 'San Francisco 49ers', 28),
(65, 'Aaron Banks', 'OG', 'San Francisco 49ers', 28),
(78, 'Ben Bartch', 'OG', 'San Francisco 49ers', 28),
(51, 'Robert Beal', 'DE', 'San Francisco 49ers', 28),
(10, 'Ronnie Bell', 'WR', 'San Francisco 49ers', 28),
(48, 'Tatum Bethune', 'LB', 'San Francisco 49ers', 28),
(97, 'Nick Bosa', 'DE', 'San Francisco 49ers', 28),
(64, 'Jake Brendel', 'C', 'San Francisco 49ers', 28),
(27, 'JiAyir Brown', 'DB', 'San Francisco 49ers', 28),
(74, 'Spencer Burford', 'OT', 'San Francisco 49ers', 28),
(59, 'DeVondre Campbell', 'LB', 'San Francisco 49ers', 28),
(99, 'Maliek Collins', 'DT', 'San Francisco 49ers', 28),
(18, 'Chris Conley', 'WR', 'San Francisco 49ers', 28),
(19, 'Jacob Cowing', 'WR', 'San Francisco 49ers', 28),
(93, 'Kalia Davis', 'DT', 'San Francisco 49ers', 28),
(5, 'Joshua Dobbs', 'QB', 'San Francisco 49ers', 28),
(92, 'Jordan Elliott', 'DT', 'San Francisco 49ers', 28),
(45, 'Demetrius Flannigan-Fowles', 'LB', 'San Francisco 49ers', 28),
(56, 'Leonard Floyd', 'LB', 'San Francisco 49ers', 28),
(90, 'Kevin Givens', 'DT', 'San Francisco 49ers', 28),
(50, 'Jalen Graham', 'LB', 'San Francisco 49ers', 28),
(0, 'Renardo Green', 'DB', 'San Francisco 49ers', 28),
(31, 'Isaac Guerendo', 'RB', 'San Francisco 49ers', 28),
(15, 'Jauan Jennings', 'WR', 'San Francisco 49ers', 28),
(44, 'Kyle Juszczyk', 'RB', 'San Francisco 49ers', 28),
(85, 'George Kittle', 'TE', 'San Francisco 49ers', 28),
(2, 'Deommodore Lenoir', 'DB', 'San Francisco 49ers', 28),
(28, 'Darrell Luter', 'DB', 'San Francisco 49ers', 28),
(24, 'Jordan Mason', 'RB', 'San Francisco 49ers', 28),
(68, 'Colton McKivitz', 'OT', 'San Francisco 49ers', 28),
(4, 'Jake Moody', 'K', 'San Francisco 49ers', 28),
(76, 'Jaylon Moore', 'OT', 'San Francisco 49ers', 28),
(6, 'Malik Mustapha', 'DB', 'San Francisco 49ers', 28),
(30, 'George Odum', 'DB', 'San Francisco 49ers', 28),
(91, 'Sam Okuayinonu', 'DT', 'San Francisco 49ers', 28),
(14, 'Ricky Pearsall', 'WR', 'San Francisco 49ers', 28),
(46, 'Taybor Pepper', 'LS', 'San Francisco 49ers', 28),
(77, 'Dominick Puni', 'OT', 'San Francisco 49ers', 28),
(13, 'Brock Purdy', 'QB', 'San Francisco 49ers', 28),
(1, 'Deebo Samuel', 'WR', 'San Francisco 49ers', 28),
(82, 'Eric Saubert', 'TE', 'San Francisco 49ers', 28),
(32, 'Patrick Taylor', 'RB', 'San Francisco 49ers', 28),
(88, 'Jake Tonges', 'TE', 'San Francisco 49ers', 28),
(7, 'Charvarius Ward', 'DB', 'San Francisco 49ers', 28),
(54, 'Fred Warner', 'LB', 'San Francisco 49ers', 28),
(71, 'Trent Williams', 'OT', 'San Francisco 49ers', 28),
(9, 'Brayden Willis', 'TE', 'San Francisco 49ers', 28),
(53, 'Dee Winters', 'LB', 'San Francisco 49ers', 28),
(3, 'Mitch Wishnowsky', 'P', 'San Francisco 49ers', 28),
(33, 'Rock Ya-Sin', 'DB', 'San Francisco 49ers', 28),
(22, 'Isaac Yiadom', 'DB', 'San Francisco 49ers', 28),
(63, 'Nick Zakelj', 'OT', 'San Francisco 49ers', 28),
(95, 'Myles Adams', 'DE', 'Seattle Seahawks', 29),
(88, 'AJ Barner', 'TE', 'Seattle Seahawks', 29),
(19, 'Jake Bobo', 'WR', 'Seattle Seahawks', 29),
(75, 'Anthony Bradford', 'OG', 'Seattle Seahawks', 29),
(86, 'Pharaoh Brown', 'TE', 'Seattle Seahawks', 29),
(22, 'Tre Brown', 'DB', 'Seattle Seahawks', 29),
(8, 'Coby Bryant', 'DB', 'Seattle Seahawks', 29),
(26, 'Zach Charbonnet', 'RB', 'Seattle Seahawks', 29),
(67, 'Charles Cross', 'OT', 'Seattle Seahawks', 29),
(4, 'Michael Dickson', 'P', 'Seattle Seahawks', 29),
(0, 'Tyrel Dodson', 'LB', 'Seattle Seahawks', 29),
(74, 'George Fant', 'OT', 'Seattle Seahawks', 29),
(87, 'Noah Fant', 'TE', 'Seattle Seahawks', 29),
(50, 'Trevis Gipson', 'LB', 'Seattle Seahawks', 29),
(58, 'Derick Hall', 'LB', 'Seattle Seahawks', 29),
(97, 'Johnathan Hankins', 'DT', 'Seattle Seahawks', 29),
(64, 'Christian Haynes', 'OG', 'Seattle Seahawks', 29),
(6, 'Sam Howell', 'QB', 'Seattle Seahawks', 29),
(65, 'Michael Jerrell', 'OT', 'Seattle Seahawks', 29),
(29, 'Josh Jobe', 'DB', 'Seattle Seahawks', 29),
(55, 'DreMont Jones', 'DE', 'Seattle Seahawks', 29),
(13, 'Ernest Jones', 'LB', 'Seattle Seahawks', 29),
(48, 'Tyrice Knight', 'LB', 'Seattle Seahawks', 29),
(63, 'Sataoa Laumea', 'OG', 'Seattle Seahawks', 29),
(16, 'Tyler Lockett', 'WR', 'Seattle Seahawks', 29),
(20, 'Julian Love', 'DB', 'Seattle Seahawks', 29),
(53, 'Boye Mafe', 'LB', 'Seattle Seahawks', 29),
(25, 'Kenny McIntosh', 'RB', 'Seattle Seahawks', 29),
(14, 'D.K. Metcalf', 'WR', 'Seattle Seahawks', 29),
(94, 'Mike Morris', 'DE', 'Seattle Seahawks', 29),
(91, 'Byron Murphy', 'DT', 'Seattle Seahawks', 29),
(5, 'Jason Myers', 'K', 'Seattle Seahawks', 29),
(51, 'Olusegun Oluwatimi', 'C', 'Seattle Seahawks', 29),
(28, 'Nehemiah Pritchett', 'DB', 'Seattle Seahawks', 29),
(90, 'Jarran Reed', 'DT', 'Seattle Seahawks', 29),
(32, 'Jerrick Reed', 'DB', 'Seattle Seahawks', 29),
(98, 'Roy Robertson-Harris', 'DT', 'Seattle Seahawks', 29),
(18, 'Josh Ross', 'LB', 'Seattle Seahawks', 29),
(38, 'Brady Russell', 'TE', 'Seattle Seahawks', 29),
(1, 'Laviska Shenault', 'WR', 'Seattle Seahawks', 29),
(7, 'Geno Smith', 'QB', 'Seattle Seahawks', 29),
(11, 'Jaxon Smith-Njigba', 'WR', 'Seattle Seahawks', 29),
(41, 'Chris Stoll', 'LS', 'Seattle Seahawks', 29),
(61, 'Jalen Sundell', 'C', 'Seattle Seahawks', 29),
(42, 'Drake Thomas', 'LB', 'Seattle Seahawks', 29),
(70, 'Laken Tomlinson', 'OG', 'Seattle Seahawks', 29),
(9, 'Kenneth Walker', 'RB', 'Seattle Seahawks', 29),
(24, 'KVon Wallace', 'DB', 'Seattle Seahawks', 29),
(82, 'Cody White', 'WR', 'Seattle Seahawks', 29),
(57, 'Connor Williams', 'C', 'Seattle Seahawks', 29),
(33, 'Dee Williams', 'DB', 'Seattle Seahawks', 29),
(99, 'Leonard Williams', 'DE', 'Seattle Seahawks', 29),
(21, 'Devon Witherspoon', 'DB', 'Seattle Seahawks', 29),
(27, 'Tariq Woolen', 'DB', 'Seattle Seahawks', 29),
(83, 'Dareke Young', 'WR', 'Seattle Seahawks', 29),
(62, 'Graham Barton', 'C', 'Tampa Bay Buccaneers', 30),
(43, 'Chris Braswell', 'LB', 'Tampa Bay Buccaneers', 30),
(68, 'Ben Bredeson', 'OG', 'Tampa Bay Buccaneers', 30),
(95, 'C.J. Brewer', 'DT', 'Tampa Bay Buccaneers', 30),
(52, 'K.J. Britt', 'LB', 'Tampa Bay Buccaneers', 30),
(97, 'Earnest Brown', 'DE', 'Tampa Bay Buccaneers', 30),
(82, 'Devin Culp', 'TE', 'Tampa Bay Buccaneers', 30),
(54, 'Lavonte David', 'LB', 'Tampa Bay Buccaneers', 30),
(0, 'YaYa Diaby', 'LB', 'Tampa Bay Buccaneers', 30),
(87, 'Payne Durham', 'TE', 'Tampa Bay Buccaneers', 30),
(13, 'Mike Evans', 'WR', 'Tampa Bay Buccaneers', 30),
(24, 'Tyrek Funderburk', 'DB', 'Tampa Bay Buccaneers', 30),
(96, 'Greg Gaines', 'DT', 'Tampa Bay Buccaneers', 30),
(92, 'William Gholston', 'DE', 'Tampa Bay Buccaneers', 30),
(16, 'Trenton Gill', 'P', 'Tampa Bay Buccaneers', 30),
(67, 'Luke Goedeke', 'OT', 'Tampa Bay Buccaneers', 30),
(48, 'Antonio Grier', 'LB', 'Tampa Bay Buccaneers', 30),
(70, 'Robert Hainsey', 'C', 'Tampa Bay Buccaneers', 30),
(90, 'Logan Hall', 'DE', 'Tampa Bay Buccaneers', 30),
(32, 'Josh Hayes', 'DB', 'Tampa Bay Buccaneers', 30),
(7, 'MarKeise Irving', 'RB', 'Tampa Bay Buccaneers', 30),
(21, 'Keenan Isaac', 'DB', 'Tampa Bay Buccaneers', 30),
(29, 'Christian Izien', 'DB', 'Tampa Bay Buccaneers', 30),
(18, 'Rakim Jarrett', 'WR', 'Tampa Bay Buccaneers', 30),
(94, 'Calijah Kancey', 'DT', 'Tampa Bay Buccaneers', 30),
(41, 'Ko Kieft', 'TE', 'Tampa Bay Buccaneers', 30),
(79, 'Elijah Klein', 'OG', 'Tampa Bay Buccaneers', 30),
(69, 'Cody Mauch', 'OG', 'Tampa Bay Buccaneers', 30),
(6, 'Baker Mayfield', 'QB', 'Tampa Bay Buccaneers', 30),
(27, 'Zyon McCollum', 'DB', 'Tampa Bay Buccaneers', 30),
(4, 'Chase McLaughlin', 'K', 'Tampa Bay Buccaneers', 30),
(15, 'Jalen McMillan', 'WR', 'Tampa Bay Buccaneers', 30),
(26, 'Kaevon Merriweather', 'DB', 'Tampa Bay Buccaneers', 30),
(81, 'Ryan Miller', 'WR', 'Tampa Bay Buccaneers', 30),
(98, 'Anthony Nelson', 'LB', 'Tampa Bay Buccaneers', 30),
(64, 'Royce Newman', 'OG', 'Tampa Bay Buccaneers', 30),
(88, 'Cade Otton', 'TE', 'Tampa Bay Buccaneers', 30),
(10, 'Trey Palmer', 'WR', 'Tampa Bay Buccaneers', 30),
(33, 'Jose Ramirez', 'LB', 'Tampa Bay Buccaneers', 30),
(51, 'J.J. Russell', 'LB', 'Tampa Bay Buccaneers', 30),
(17, 'Sterling Shepard', 'WR', 'Tampa Bay Buccaneers', 30),
(77, 'Justin Skule', 'OT', 'Tampa Bay Buccaneers', 30),
(23, 'Tykee Smith', 'DB', 'Tampa Bay Buccaneers', 30),
(37, 'Tavierre Thomas', 'DB', 'Tampa Bay Buccaneers', 30),
(2, 'Kyle Trask', 'QB', 'Tampa Bay Buccaneers', 30),
(45, 'Zach Triner', 'LS', 'Tampa Bay Buccaneers', 30),
(9, 'Joe Tryon-Shoyinka', 'LB', 'Tampa Bay Buccaneers', 30),
(44, 'Sean Tucker', 'RB', 'Tampa Bay Buccaneers', 30),
(50, 'Vita Vea', 'DT', 'Tampa Bay Buccaneers', 30),
(1, 'Rachaad White', 'RB', 'Tampa Bay Buccaneers', 30),
(3, 'Jordan Whitehead', 'DB', 'Tampa Bay Buccaneers', 30),
(31, 'Antoine Winfield', 'DB', 'Tampa Bay Buccaneers', 30),
(78, 'Tristan Wirfs', 'OT', 'Tampa Bay Buccaneers', 30),
(23, 'Tre Avery', 'DB', 'Tennessee Titans', 31),
(39, 'Darrell Baker', 'DB', 'Tennessee Titans', 31),
(17, 'Jerome Baker', 'LB', 'Tennessee Titans', 31),
(83, 'Tyler Boyd', 'WR', 'Tennessee Titans', 31),
(44, 'Mike Brown', 'DB', 'Tennessee Titans', 31),
(29, 'Jarvis Brownlee', 'DB', 'Tennessee Titans', 31),
(60, 'Daniel Brunskill', 'OG', 'Tennessee Titans', 31),
(36, 'Julius Chestnut', 'RB', 'Tennessee Titans', 31),
(91, 'Keondre Coburn', 'DT', 'Tennessee Titans', 31),
(46, 'Morgan Cox', 'LS', 'Tennessee Titans', 31),
(79, 'Lloyd Cushenberry', 'C', 'Tennessee Titans', 31),
(28, 'Quandre Diggs', 'DB', 'Tennessee Titans', 31),
(6, 'Nick Folk', 'K', 'Tennessee Titans', 31),
(99, 'Ali Gaye', 'LB', 'Tennessee Titans', 31),
(50, 'Jack Gibbens', 'LB', 'Tennessee Titans', 31),
(57, 'Luke Gifford', 'LB', 'Tennessee Titans', 31),
(51, 'Cedric Gray', 'LB', 'Tennessee Titans', 31),
(0, 'Justin Hardee', 'DB', 'Tennessee Titans', 31),
(92, 'Jaylen Harrell', 'LB', 'Tennessee Titans', 31),
(37, 'Amani Hooker', 'DB', 'Tennessee Titans', 31),
(19, 'JhaQuan Jackson', 'WR', 'Tennessee Titans', 31),
(32, 'Gabe Jeudy-Lally', 'DB', 'Tennessee Titans', 31),
(69, 'Sebastian Joseph', 'DE', 'Tennessee Titans', 31),
(25, 'Joshua Kelley', 'RB', 'Tennessee Titans', 31),
(49, 'Arden Key', 'LB', 'Tennessee Titans', 31),
(58, 'Harold Landry', 'LB', 'Tennessee Titans', 31),
(55, 'JC Latham', 'OT', 'Tennessee Titans', 31),
(62, 'Corey Levin', 'C', 'Tennessee Titans', 31),
(8, 'Will Levis', 'QB', 'Tennessee Titans', 31),
(97, 'James Lynch', 'DT', 'Tennessee Titans', 31),
(88, 'David Martin-Robinson', 'TE', 'Tennessee Titans', 31),
(21, 'Roger McCreary', 'DB', 'Tennessee Titans', 31),
(56, 'Kenneth Murray', 'LB', 'Tennessee Titans', 31),
(61, 'John Ojukwu', 'OT', 'Tennessee Titans', 31),
(85, 'Chigoziem Okonkwo', 'TE', 'Tennessee Titans', 31),
(80, 'Bryce Oliver', 'WR', 'Tennessee Titans', 31),
(78, 'Nicholas Petit-Frere', 'OT', 'Tennessee Titans', 31),
(20, 'Tony Pollard', 'RB', 'Tennessee Titans', 31),
(75, 'Dillon Radunz', 'OT', 'Tennessee Titans', 31),
(41, 'Otis Reese', 'LB', 'Tennessee Titans', 31),
(0, 'Calvin Ridley', 'WR', 'Tennessee Titans', 31),
(11, 'Mason Rudolph', 'QB', 'Tennessee Titans', 31),
(3, 'Trevor Siemian', 'QB', 'Tennessee Titans', 31),
(98, 'Jeffery Simmons', 'DT', 'Tennessee Titans', 31),
(77, 'Peter Skoronski', 'OT', 'Tennessee Titans', 31),
(38, 'LJarius Sneed', 'DB', 'Tennessee Titans', 31),
(2, 'Tyjae Spears', 'RB', 'Tennessee Titans', 31),
(4, 'Ryan Stonehouse', 'P', 'Tennessee Titans', 31),
(93, 'TVondre Sweat', 'DT', 'Tennessee Titans', 31),
(84, 'Nick Vannett', 'TE', 'Tennessee Titans', 31),
(72, 'Leroy Watson', 'OT', 'Tennessee Titans', 31),
(15, 'Nick Westbrook', 'WR', 'Tennessee Titans', 31),
(81, 'Josh Whyle', 'TE', 'Tennessee Titans', 31),
(52, 'James Williams', 'LB', 'Tennessee Titans', 31),
(24, 'Julius Wood', 'DB', 'Tennessee Titans', 31),
(67, 'Nick Allegretti', 'OG', 'Washington Commanders', 32),
(92, 'Dorance Armstrong', 'DE', 'Washington Commanders', 32),
(87, 'John Bates', 'TE', 'Washington Commanders', 32),
(57, 'Nick Bellore', 'LB', 'Washington Commanders', 32),
(63, 'Tyler Biadasz', 'C', 'Washington Commanders', 32),
(2, 'Dyami Brown', 'WR', 'Washington Commanders', 32),
(85, 'Noah Brown', 'WR', 'Washington Commanders', 32),
(35, 'Percy Butler', 'DB', 'Washington Commanders', 32),
(11, 'Jeremy Chinn', 'DB', 'Washington Commanders', 32),
(74, 'Brandon Coleman', 'OT', 'Washington Commanders', 32),
(76, 'Samuel Cosmi', 'OG', 'Washington Commanders', 32),
(5, 'Jayden Daniels', 'QB', 'Washington Commanders', 32),
(24, 'Michael Davis', 'DB', 'Washington Commanders', 32),
(64, 'Sheldon Day', 'DT', 'Washington Commanders', 32),
(60, 'Michael Deiter', 'OG', 'Washington Commanders', 32),
(16, 'Jeff Driskel', 'QB', 'Washington Commanders', 32),
(30, 'Austin Ekeler', 'RB', 'Washington Commanders', 32),
(86, 'Zach Ertz', 'TE', 'Washington Commanders', 32),
(99, 'Clelin Ferrell', 'DE', 'Washington Commanders', 32),
(13, 'Emmanuel Forbes', 'DB', 'Washington Commanders', 32),
(22, 'Darrick Forrest', 'DB', 'Washington Commanders', 32),
(6, 'Dante Fowler Jr.', 'LB', 'Washington Commanders', 32),
(45, 'Dominique Hampton', 'DB', 'Washington Commanders', 32),
(96, 'Jalyn Holmes', 'DT', 'Washington Commanders', 32),
(1, 'Noah Igbinoghene', 'DB', 'Washington Commanders', 32),
(78, 'Cornelius Lucas', 'OT', 'Washington Commanders', 32),
(4, 'Frankie Luvu', 'LB', 'Washington Commanders', 32),
(58, 'Jordan Magee', 'LB', 'Washington Commanders', 32),
(18, 'Marcus Mariota', 'QB', 'Washington Commanders', 32),
(20, 'Jartavius Martin', 'DB', 'Washington Commanders', 32),
(98, 'Phidarian Mathis', 'DT', 'Washington Commanders', 32),
(12, 'Luke McCaffrey', 'WR', 'Washington Commanders', 32),
(17, 'Terry McLaurin', 'WR', 'Washington Commanders', 32),
(26, 'Jeremy McNichols', 'RB', 'Washington Commanders', 32),
(95, 'JerZhan Newton', 'DT', 'Washington Commanders', 32),
(97, 'Efe Obada', 'DE', 'Washington Commanders', 32),
(69, 'Tyler Ott', 'LS', 'Washington Commanders', 32),
(40, 'Tyler Owens', 'DB', 'Washington Commanders', 32),
(75, 'Chris Paul', 'OG', 'Washington Commanders', 32),
(94, 'Daron Payne', 'DT', 'Washington Commanders', 32),
(39, 'Jeremy Reaves', 'DB', 'Washington Commanders', 32),
(8, 'Brian Robinson', 'RB', 'Washington Commanders', 32),
(23, 'Christopher Rodriguez', 'RB', 'Washington Commanders', 32),
(0, 'Mike Sainristil', 'DB', 'Washington Commanders', 32),
(73, 'Trenton Scott', 'OT', 'Washington Commanders', 32),
(3, 'Austin Seibert', 'K', 'Washington Commanders', 32),
(82, 'Ben Sinnott', 'TE', 'Washington Commanders', 32),
(25, 'Benjamin St-Juste', 'DB', 'Washington Commanders', 32),
(54, 'Bobby Wagner', 'LB', 'Washington Commanders', 32),
(32, 'Mykal Walker', 'LB', 'Washington Commanders', 32),
(10, 'Tress Way', 'P', 'Washington Commanders', 32),
(71, 'Andrew Wylie', 'OT', 'Washington Commanders', 32),
(41, 'Colson Yankoff', 'TE', 'Washington Commanders', 32),
(14, 'Olamide Zaccheaus', 'WR', 'Washington Commanders', 32);

